/* SPDX-License-Identifier: Apache-2.0
 * BirdNET-STM32 — SD card batch inference application
 *
 * Main loop: init board → mount SD → scan audio/ → for each WAV:
 *   Depending on APP_AUDIO_FRONTEND:
 *     hybrid:      STFT on Cortex-M55 → NPU inference
 *     raw:         raw waveform → NPU inference (no STFT)
 *     precomputed: STFT + mel filterbank on Cortex-M55 → NPU inference
 *
 * Uses the NPU_Validation init infrastructure (misc_toolbox,
 * system_clock_config, npu_cache, mcu_cache) and adds BSP SD + FatFs +
 * custom STFT on top.
 *
 * Target board: STM32N6570-DK
 */

#include <stdio.h>
#include <string.h>
#include <math.h>

/* STM32 HAL */
#include "stm32n6xx_hal.h"
#include "main.h"

/* NPU_Validation infrastructure */
#include "misc_toolbox.h"
#include "mcu_cache.h"

/* LL_ATON NPU runtime (generated by stedgeai) */
#include "ll_aton_NN_interface.h"
#include "ll_aton_osal.h"
#include "ll_aton_rt_user_api.h"
#include "ll_aton_runtime.h"
#include "network.h"

/* LL_ATON network instance for the Default network */
LL_ATON_DECLARE_NAMED_NN_INSTANCE_AND_INTERFACE(Default);

/* Application modules */
#include "app_config.h"

/* Define to dump, per file: the NPU input signature, the int8 tensor produced
 * by the software QuantizeLinear epoch, the weight bytes read from external
 * flash, the executed epoch-block count, and the raw output. Each is directly
 * comparable against a host run on the same WAV, which is how the board's data
 * path was verified stage by stage. Left in (inactive) because the host/board
 * mismatch is not yet resolved. */
/* #define APP_DEBUG_IO 1 */
#include "app_labels.h"
#include "wav_reader.h"
#include "audio_stft.h"
#include "audio_mel.h"
#include "sd_handler.h"

/* Clock config (from NPU_Validation) */
extern void SystemClock_Config_ResetClocks(void);
extern void SystemClock_Config_HSI_overdrive(void);
extern void SystemClock_Config_HSI_no_overdrive(void);
extern void SystemClock_Config_HSI_400(void);

/* Stub used as GDB breakpoint marker by n6_loader. */
static void aiValidationInit(void) { __asm volatile("nop"); }

/* ---- UART printf redirect ------------------------------------------------ */
/* NPU_Validation's misc_toolbox.c provides UartHandle (USART1).
 * syscalls.c provides _write() calling __io_putchar() (weak).
 * We provide the strong definition here. */

int __io_putchar(int ch)
{
    HAL_UART_Transmit(&UartHandle, (uint8_t *)&ch, 1, HAL_MAX_DELAY);
    return ch;
}

/* ---- Working memory ------------------------------------------------------ */
static float audio_buf[APP_CHUNK_SAMPLES]
    __attribute__((aligned(32)));

#if APP_AUDIO_FRONTEND == APP_FRONTEND_HYBRID
/* hybrid: STFT output is [fft_bins, spec_width] */
static float spec_buf[APP_FFT_BINS * APP_SPEC_WIDTH]
    __attribute__((aligned(32)));
#elif APP_AUDIO_FRONTEND == APP_FRONTEND_PRECOMPUTED
/* precomputed: STFT then mel → [num_mels, spec_width] */
static float spec_buf[APP_FFT_BINS * APP_SPEC_WIDTH]
    __attribute__((aligned(32)));
static float mel_buf[APP_NUM_MELS * APP_SPEC_WIDTH]
    __attribute__((aligned(32)));
#endif
/* raw: audio_buf is fed directly to NPU, no extra buffer needed */

#if APP_AUDIO_FRONTEND == APP_FRONTEND_RAW
static void peak_normalize(float *audio, uint32_t num_samples)
{
    float peak = 0.0f;

    for (uint32_t i = 0; i < num_samples; i++) {
        float magnitude = fabsf(audio[i]);
        if (magnitude > peak)
            peak = magnitude;
    }

    /* Match the raw-audio preprocessing used for training and PTQ calibration. */
    float scale = peak + 1.0e-6f;
    for (uint32_t i = 0; i < num_samples; i++)
        audio[i] /= scale;
}
#endif

/* ---- NPU inference ------------------------------------------------------- */

/* The runtime and the network instance are initialised once at start-up; each
 * inference only resets the instance and drives the epoch blocks to completion.
 *
 * LL_ATON_RT_Main() must not be used here. ST ships it as a single-inference
 * template: it wraps the epoch loop in RuntimeInit()/RuntimeDeInit(), so calling
 * it per file re-runs LL_ATON_Init() -- resetting the ATON hardware -- *after*
 * the input has already been staged in the activation pool, which the input
 * buffer shares with the output. The network then runs on a clobbered input and
 * returns the same near-constant scores for every file. This ordering (stage
 * input, reset instance, run epochs) matches ST's own NPU_Validation wrapper.
 */
static bool run_inference(const float *spect, float *output)
{
    const LL_Buffer_InfoTypeDef *in_info = LL_ATON_Input_Buffers_Info_Default();
    const LL_Buffer_InfoTypeDef *out_info = LL_ATON_Output_Buffers_Info_Default();

    uint32_t input_bytes = in_info->shape[1] * in_info->shape[2] * sizeof(float);
    uint32_t output_bytes = out_info->shape[2] * sizeof(float);

    float *input_ptr = (float *)(in_info->addr_base.i + in_info->offset_start);

    /* Reset FIRST, then stage the input. The network is built with
     * `allocate-inputs`, so the input tensor lives inside the activation pool;
     * resetting the instance re-initialises that pool and would wipe an input
     * written beforehand. */
    LL_ATON_RT_Reset_Network(&NN_Instance_Default);

    // Copy spectrogram into NPU
    memcpy(input_ptr, spect, input_bytes);

    /* Whole-cache clean + invalidate, mirroring ST's _force_clean_cache_subsystem.
     *
     * Cleaning just the input range is not enough. The activation pool is reused
     * across the graph: the NPU writes intermediate tensors into it by DMA,
     * bypassing the D-cache, and the software epochs (Transpose, Dequantize)
     * then read those tensors back with the CPU. Any line this core still holds
     * for that region -- from staging the input, or from the previous file --
     * is stale, so the software epochs would compute on old data. Clean flushes
     * our input to RAM; invalidate drops every stale line so later CPU reads
     * refetch what the NPU actually wrote. */
    SCB_CleanInvalidateDCache();

#ifdef APP_DEBUG_IO
    /* Read the input tensor back at run time to prove what the NPU will see. */
    SCB_InvalidateDCache_by_Addr((uint32_t *)input_ptr, (int32_t)input_bytes);
    printf("  [DBG-STAGED] s0=%d s1=%d s1000=%d (x1e6)\n",
           (int)(input_ptr[0] * 1e6f), (int)(input_ptr[1] * 1e6f),
           (int)(input_ptr[1000] * 1e6f));
#endif

    LL_ATON_RT_RetValues_t rt_ret;
#ifdef APP_DEBUG_IO
    int dbg_block = 0;
#endif
    do {
        rt_ret = LL_ATON_RT_RunEpochBlock(&NN_Instance_Default);
        if (rt_ret == LL_ATON_RT_WFE)
            LL_ATON_OSAL_WFE();
#ifdef APP_DEBUG_IO
        if (dbg_block++ == 0) {
            /* Epoch 2 (the pure-SW QuantizeLinear) is the first epoch block. It
             * writes the int8 view of the input at input+240000. If this does
             * not change between files, the SW epoch's result never reaches the
             * NPU; if it does change, the fault is downstream. */
            const int8_t *q = (const int8_t *)input_ptr + 240000;
            SCB_InvalidateDCache_by_Addr((uint32_t *)(void *)q, 64);
            printf("  [DBG-Q] %d %d %d %d %d %d %d %d\n",
                   q[0], q[1], q[2], q[3], q[1000], q[2000], q[30000], q[59999]);
        }
#endif
    } while (rt_ret != LL_ATON_RT_DONE);
#ifdef APP_DEBUG_IO
    /* The generated graph has 46 epochs / ~44 epoch blocks. A much smaller
     * count means the HW epochs are being skipped rather than executed. */
    printf("  [DBG-EPOCHS] blocks=%d\n", dbg_block);
#endif

    const float *output_ptr = (const float *)(out_info->addr_base.i + out_info->offset_start);

    memcpy(output, output_ptr, output_bytes);
    return true;
}

/* ---- Top-K print helper -------------------------------------------------- */
static void print_top_k(const char *filename, const float *scores, int k)
{
    int indices[APP_NUM_CLASSES];
    for (int i = 0; i < APP_NUM_CLASSES; i++)
        indices[i] = i;

    for (int i = 0; i < k && i < APP_NUM_CLASSES; i++) {
        for (int j = i + 1; j < APP_NUM_CLASSES; j++) {
            if (scores[indices[j]] > scores[indices[i]]) {
                int tmp = indices[i];
                indices[i] = indices[j];
                indices[j] = tmp;
            }
        }
    }

    printf("  %s:\n", filename);
    for (int i = 0; i < k && i < APP_NUM_CLASSES; i++) {
        int ci = indices[i];
        if (scores[ci] < APP_SCORE_THRESHOLD)
            break;
        int pct = (int)(scores[ci] * 1000.0f);
        printf("    [%d] %s: %d.%d%%\n", i + 1, APP_LABELS[ci], pct / 10, pct % 10);
    }
}

/* ---- Main ---------------------------------------------------------------- */

int main(void)
{
    /* ---- Board init (mirrors NPU_Validation main.c) ---- */
    printf("[INIT] Setting vector table...\n");
    set_vector_table_addr();
    HAL_Init();
    SystemClock_Config_ResetClocks();
    system_init_post();
    printf("[INIT] HAL and clocks configured\n");

    printf("[INIT] Enabling caches...\n");
    SCB_EnableICache();
    SCB_EnableDCache();

    /* Clock selection. The NPU is only in spec at 800 MHz / 1 GHz once VDDCORE
     * has been raised, so a build that does not raise it must not select those
     * speeds: the NPU still runs and still reports plausible timings, but its
     * results are wrong. Without overdrive, use ST's all-400 MHz profile. */
#if USE_OVERDRIVE
    printf("[INIT] Switching to overdrive (CPU @ 800 MHz, NPU @ 1 GHz)...\n");
    upscale_vddcore_level();
    SystemClock_Config_HSI_overdrive();
#elif defined(NO_OVD_CLK400)
    printf("[INIT] No overdrive (CPU/NIC/NOC/NPU @ 400 MHz)...\n");
    SystemClock_Config_HSI_400();
#else
    printf("[INIT] No overdrive (CPU @ 600 MHz, NPU @ 800 MHz)...\n");
    SystemClock_Config_HSI_no_overdrive();
#endif
    fuse_vddio();

    CLEAR_BIT(SCB->SCR, SCB_SCR_SLEEPDEEP_Msk);

    printf("[INIT] Configuring UART...\n");
    UART_Config();
    /* From here on, printf is reliable at full baud rate. */

    /* ---- External memory init (xSPI RAM + NOR flash) ---- */
    printf("[INIT] Configuring external memories...\n");
    {
        BSP_XSPI_NOR_Init_t Flash;
        BSP_XSPI_RAM_Init(0);
        BSP_XSPI_RAM_EnableMemoryMappedMode(0);
        MODIFY_REG(XSPI1->CR, XSPI_CR_NOPREF,
                   HAL_XSPI_AUTOMATIC_PREFETCH_DISABLE);
        Flash.InterfaceMode = MX66UW1G45G_OPI_MODE;
        Flash.TransferRate  = MX66UW1G45G_DTR_TRANSFER;
        if (BSP_XSPI_NOR_Init(0, &Flash) != BSP_ERROR_NONE) {
            printf("[ERROR] xSPI NOR init failed\n");
            while (1) {}
        }
        BSP_XSPI_NOR_EnableMemoryMappedMode(0);
    }
    printf("[OK] External memories mapped\n");

    printf("[INIT] Configuring NPU...\n");
    NPU_Config();
    RISAF_Config();
    set_clk_sleep_mode();

    /* n6_loader uses this line to set a GDB breakpoint during flash. */
    aiValidationInit();

    printf("\n=== BirdNET-STM32 SD Card Inference ===\n");
    unsigned long chunk_seconds = APP_CHUNK_SAMPLES / APP_SAMPLE_RATE;
    unsigned long chunk_milliseconds =
        ((APP_CHUNK_SAMPLES % APP_SAMPLE_RATE) * 1000UL) / APP_SAMPLE_RATE;
#if APP_AUDIO_FRONTEND == APP_FRONTEND_RAW
    printf("[INFO] Frontend: raw (waveform → NPU)\n");
    printf("[INFO] Sample rate: %d Hz, chunk: %lu.%03lus (%d samples), classes: %d\n",
           (int)APP_SAMPLE_RATE, chunk_seconds, chunk_milliseconds,
           (int)APP_CHUNK_SAMPLES, APP_NUM_CLASSES);
#elif APP_AUDIO_FRONTEND == APP_FRONTEND_PRECOMPUTED
    printf("[INFO] Frontend: librosa (STFT + mel on M55 → NPU)\n");
    printf("[INFO] Sample rate: %d Hz, chunk: %lu.%03lus, FFT: %d, hop: %d, "
           "spec: %dx%d, mels: %d, classes: %d\n",
           (int)APP_SAMPLE_RATE, chunk_seconds, chunk_milliseconds, APP_FFT_LENGTH,
           APP_HOP_LENGTH, APP_FFT_BINS, APP_SPEC_WIDTH, APP_NUM_MELS, APP_NUM_CLASSES);
    mel_init(APP_FFT_BINS, APP_NUM_MELS, APP_SAMPLE_RATE, 150.0f,
             (float)(APP_SAMPLE_RATE / 2));
    printf("[OK] Mel filterbank initialized\n");
#else
    printf("[INFO] Frontend: hybrid (STFT on M55 → NPU)\n");
    printf("[INFO] Sample rate: %d Hz, chunk: %lu.%03lus, FFT: %d, hop: %d, "
           "spec: %dx%d, classes: %d\n",
           (int)APP_SAMPLE_RATE, chunk_seconds, chunk_milliseconds, APP_FFT_LENGTH,
           APP_HOP_LENGTH, APP_FFT_BINS, APP_SPEC_WIDTH, APP_NUM_CLASSES);
#endif

    /* ---- NPU network init ---- */
    printf("[INIT] Initialising NPU network...\n");
    if (!LL_ATON_EC_Network_Init_Default()) {
        printf("[ERROR] NPU network init failed\n");
        while (1) {}
    }

    /* Bring up the ATON runtime and the network instance once, for the lifetime
     * of the application. run_inference() only resets the instance per file. */
    LL_ATON_RT_RuntimeInit();
    LL_ATON_RT_Init_Network(&NN_Instance_Default);

#ifdef APP_DEBUG_IO
    {
        /* The NPU reads the weight blob from memory-mapped external flash. If
         * these bytes do not match network_atonbuf.xSPI2.raw, every HW epoch is
         * convolving against garbage. */
        const int8_t *w = (const int8_t *)0x71000000UL;
        printf("[DBG-W] %d %d %d %d %d %d %d %d (expect 47 -15 26 67 23 -37 -32 -58)\n",
               w[0], w[1], w[2], w[3], w[4], w[5], w[6], w[7]);
    }
#endif

    const LL_Buffer_InfoTypeDef *in_info  = LL_ATON_Input_Buffers_Info_Default();
    const LL_Buffer_InfoTypeDef *out_info = LL_ATON_Output_Buffers_Info_Default();
    if (in_info && in_info->name) {
        printf("[OK] NPU input:  \"%s\"  %lu bytes\n",
               in_info->name,
               (unsigned long)(in_info->offset_end - in_info->offset_start));
    }
    if (out_info && out_info->name) {
        printf("[OK] NPU output: \"%s\"  %lu bytes\n",
               out_info->name,
               (unsigned long)(out_info->offset_end - out_info->offset_start));
    }

    /* ---- Mount SD card ---- */
    printf("[INIT] Mounting SD card (SDMMC2)...\n");
    if (!sd_mount()) {
        printf("[ERROR] SD card mount failed\n");
        while (1) {}
    }
    printf("[OK] SD card mounted\n");

    /* ---- Labels ---- */
    printf("[OK] %d class labels compiled in\n", APP_NUM_CLASSES);

    /* ---- Scan audio directory ---- */
    printf("[INIT] Scanning /%s/ for .wav files...\n", APP_AUDIO_DIR);
    static SdFileList file_list;
    uint32_t num_files = sd_scan_audio_dir(APP_AUDIO_DIR, &file_list);
    printf("[OK] Found %lu audio files\n", (unsigned long)num_files);

    if (num_files == 0) {
        printf("[WARN] No .wav files found. Done.\n");
        printf("\n=== DONE ===\n");
        printf("Processed: 0 / 0 files (0 errors)\n");
        sd_unmount();
        while (1) {}
    }

    /* ---- Process each file ---- */
    float scores[APP_NUM_CLASSES];
    uint32_t processed = 0;
    uint32_t errors = 0;
    uint32_t total_read_ms   = 0;
    uint32_t total_stft_ms   = 0;
    uint32_t total_npu_ms    = 0;

    for (uint32_t i = 0; i < num_files; i++) {
        const char *filepath = file_list.paths[i];
        const char *basename = strrchr(filepath, '/');
        basename = basename ? basename + 1 : filepath;

        printf("\n[%lu/%lu] %s\n", (unsigned long)(i + 1),
               (unsigned long)num_files, basename);

        FIL fp;
        if (f_open(&fp, filepath, FA_READ) != FR_OK) {
            printf("  [SKIP] Cannot open file\n");
            errors++;
            continue;
        }

        WavInfo wav;
        if (!wav_parse_header(&fp, &wav)) {
            printf("  [SKIP] Invalid WAV format\n");
            f_close(&fp);
            errors++;
            continue;
        }

        printf("  [WAV] %lu Hz, %d-bit, %d ch, %lu samples\n",
               (unsigned long)wav.sample_rate, wav.bits_per_sample,
               wav.num_channels, (unsigned long)wav.num_samples);

        if (wav.sample_rate != APP_SAMPLE_RATE) {
            printf("  [SKIP] Sample rate %lu != %d\n",
                   (unsigned long)wav.sample_rate, APP_SAMPLE_RATE);
            f_close(&fp);
            errors++;
            continue;
        }

        /* Read first chunk */
        uint32_t t0 = HAL_GetTick();
        wav_read_chunk_f32(&fp, &wav, 0, APP_CHUNK_SAMPLES, audio_buf);
        f_close(&fp);
        uint32_t read_ms = HAL_GetTick() - t0;
        total_read_ms += read_ms;

        /* Prepare NPU input based on frontend mode */
        uint32_t stft_ms = 0;
        const float *npu_input = NULL;

#if APP_AUDIO_FRONTEND == APP_FRONTEND_RAW
        /* Raw: reproduce training-time normalization, then feed the waveform. */
        peak_normalize(audio_buf, APP_CHUNK_SAMPLES);
        npu_input = audio_buf;
#ifdef APP_DEBUG_IO
        {
            /* Signature of the tensor actually handed to the NPU, so a host run
             * on the same file can be compared value for value. */
            float dbg_min = audio_buf[0], dbg_max = audio_buf[0], dbg_absmean = 0.0f;
            for (uint32_t s = 0; s < APP_CHUNK_SAMPLES; s++) {
                float v = audio_buf[s];
                if (v < dbg_min) dbg_min = v;
                if (v > dbg_max) dbg_max = v;
                dbg_absmean += fabsf(v);
            }
            dbg_absmean /= (float)APP_CHUNK_SAMPLES;
            /* Scaled integers: the link uses nano.specs without _printf_float. */
            printf("  [DBG-IN] min=%d max=%d absmean=%d s0=%d s1=%d s1000=%d (x1e6)\n",
                   (int)(dbg_min * 1e6f), (int)(dbg_max * 1e6f), (int)(dbg_absmean * 1e6f),
                   (int)(audio_buf[0] * 1e6f), (int)(audio_buf[1] * 1e6f),
                   (int)(audio_buf[1000] * 1e6f));
        }
#endif
#elif APP_AUDIO_FRONTEND == APP_FRONTEND_PRECOMPUTED
        /* Librosa: STFT → mel filterbank on M55 */
        t0 = HAL_GetTick();
        stft_magnitude(audio_buf, APP_CHUNK_SAMPLES,
                       APP_FFT_LENGTH, APP_HOP_LENGTH,
                       APP_SPEC_WIDTH, spec_buf);
        mel_filterbank(spec_buf, APP_FFT_BINS, APP_SPEC_WIDTH,
                       APP_NUM_MELS, mel_buf);
        stft_ms = HAL_GetTick() - t0;
        npu_input = mel_buf;
#else
        /* Hybrid: STFT on M55, mel conversion inside NPU model */
        t0 = HAL_GetTick();
        stft_magnitude(audio_buf, APP_CHUNK_SAMPLES,
                       APP_FFT_LENGTH, APP_HOP_LENGTH,
                       APP_SPEC_WIDTH, spec_buf);
        stft_ms = HAL_GetTick() - t0;
        npu_input = spec_buf;
#endif
        total_stft_ms += stft_ms;

        /* Run NPU inference */
        t0 = HAL_GetTick();
        if (!run_inference(npu_input, scores)) {
            printf("  [ERROR] Inference failed\n");
            errors++;
            continue;
        }
        uint32_t npu_ms = HAL_GetTick() - t0;
#ifdef APP_DEBUG_IO
        printf("  [DBG-OUT] %d %d %d %d %d (x1e6)\n",
               (int)(scores[0] * 1e6f), (int)(scores[1] * 1e6f), (int)(scores[2] * 1e6f),
               (int)(scores[3] * 1e6f), (int)(scores[4] * 1e6f));
#endif
        total_npu_ms += npu_ms;

        printf("  [BENCH] read=%lums stft=%lums npu=%lums total=%lums\n",
               (unsigned long)read_ms, (unsigned long)stft_ms,
               (unsigned long)npu_ms,
               (unsigned long)(read_ms + stft_ms + npu_ms));

        /* Print top-K results over UART */
        print_top_k(basename, scores, APP_TOP_K);
        processed++;
    }

    /* ---- Summary ---- */
    printf("\n=== DONE ===\n");
    printf("Processed: %lu / %lu files (%lu errors)\n",
           (unsigned long)processed, (unsigned long)num_files,
           (unsigned long)errors);
    if (processed > 0) {
        printf("Benchmark: read=%lums stft=%lums npu=%lums total=%lums "
               "(avg read=%lums stft=%lums npu=%lums total=%lums)\n",
               (unsigned long)total_read_ms, (unsigned long)total_stft_ms,
               (unsigned long)total_npu_ms,
               (unsigned long)(total_read_ms + total_stft_ms + total_npu_ms),
               (unsigned long)(total_read_ms / processed),
               (unsigned long)(total_stft_ms / processed),
               (unsigned long)(total_npu_ms / processed),
               (unsigned long)((total_read_ms + total_stft_ms + total_npu_ms) / processed));
    }

    sd_unmount();
    printf("[OK] SD card unmounted. Halting.\n");

    while (1) {
        /* Halt */
    }
}

void Error_Handler(void)
{
    while (1) {}
}

#ifdef USE_FULL_ASSERT
void assert_failed(uint8_t *file, uint32_t line)
{
    (void)file;
    (void)line;
    while (1) {}
}
#endif
