/* SPDX-License-Identifier: Apache-2.0
 * BirdNET-STM32 — SD card batch inference application
 *
 * Main loop: init board → mount SD → scan audio/ → for each WAV:
 *   STFT on Cortex-M55 → NPU inference → print results over UART.
 *
 * Replaces NPU_Validation's main.c.  Uses the same init infrastructure
 * (misc_toolbox, system_clock_config, npu_cache, mcu_cache) and adds
 * BSP SD + FatFs + custom STFT on top.
 *
 * Target board: STM32N6570-DK
 */

#include <stdio.h>
#include <string.h>
#include <math.h>

/* STM32 HAL */
#include "stm32n6xx_hal.h"

/* NPU_Validation infrastructure */
#include "misc_toolbox.h"
#include "mcu_cache.h"

/* LL_ATON NPU runtime (generated by stedgeai) */
#include "ll_aton_NN_interface.h"

/* Application modules */
#include "app_config.h"
#include "app_labels.h"
#include "wav_reader.h"
#include "audio_stft.h"
#include "sd_handler.h"

/* Clock config (from NPU_Validation) */
extern void SystemClock_Config_ResetClocks(void);
extern void SystemClock_Config_HSI_overdrive(void);

/* ---- UART printf redirect ------------------------------------------------ */
/* NPU_Validation's misc_toolbox.c provides UartHandle (USART1).
 * syscalls.c provides _write() calling __io_putchar() (weak).
 * We provide the strong definition here. */

int __io_putchar(int ch)
{
    HAL_UART_Transmit(&UartHandle, (uint8_t *)&ch, 1, HAL_MAX_DELAY);
    return ch;
}

/* ---- Working memory ------------------------------------------------------ */
static float audio_buf[APP_CHUNK_SAMPLES]
    __attribute__((aligned(32)));

static float spec_buf[APP_FFT_BINS * APP_SPEC_WIDTH]
    __attribute__((aligned(32)));

/* ---- NPU inference ------------------------------------------------------- */

static bool run_inference(const float *spec, float *output)
{
    const LL_Buffer_InfoTypeDef *in_info  = LL_ATON_Input_Buffers_Info_Default();
    const LL_Buffer_InfoTypeDef *out_info = LL_ATON_Output_Buffers_Info_Default();

    if (!in_info || !in_info->name || !out_info || !out_info->name)
        return false;

    float *input_ptr = (float *)((uint8_t *)in_info->addr_base + in_info->offset_start);
    uint32_t input_bytes = in_info->offset_end - in_info->offset_start;

    memcpy(input_ptr, spec, input_bytes);
    SCB_CleanDCache_by_Addr((uint32_t *)input_ptr, (int32_t)input_bytes);

    LL_ATON_EC_Inference_Init_Default();

    while (LL_ATON_RT_Main_Default() != LL_ATON_RT_DONE) {
        /* busy-wait */
    }

    const float *output_ptr = (const float *)((uint8_t *)out_info->addr_base + out_info->offset_start);
    uint32_t output_bytes = out_info->offset_end - out_info->offset_start;

    SCB_InvalidateDCache_by_Addr((uint32_t *)output_ptr, (int32_t)output_bytes);

    memcpy(output, output_ptr, output_bytes);
    return true;
}

/* ---- Top-K print helper -------------------------------------------------- */
static void print_top_k(const char *filename, const float *scores, int k)
{
    int indices[APP_NUM_CLASSES];
    for (int i = 0; i < APP_NUM_CLASSES; i++)
        indices[i] = i;

    for (int i = 0; i < k && i < APP_NUM_CLASSES; i++) {
        for (int j = i + 1; j < APP_NUM_CLASSES; j++) {
            if (scores[indices[j]] > scores[indices[i]]) {
                int tmp = indices[i];
                indices[i] = indices[j];
                indices[j] = tmp;
            }
        }
    }

    printf("  %s:\n", filename);
    for (int i = 0; i < k && i < APP_NUM_CLASSES; i++) {
        int ci = indices[i];
        if (scores[ci] < APP_SCORE_THRESHOLD)
            break;
        int pct = (int)(scores[ci] * 1000.0f);
        printf("    [%d] %s: %d.%d%%\n", i + 1, APP_LABELS[ci], pct / 10, pct % 10);
    }
}

/* ---- Main ---------------------------------------------------------------- */

int main(void)
{
    /* ---- Board init (mirrors NPU_Validation main.c) ---- */
    printf("[INIT] Setting vector table...\n");
    set_vector_table_addr();
    HAL_Init();
    SystemClock_Config_ResetClocks();
    system_init_post();
    printf("[INIT] HAL and clocks configured\n");

    printf("[INIT] Enabling caches...\n");
    SCB_EnableICache();
    SCB_EnableDCache();

    printf("[INIT] Switching to overdrive...\n");
    upscale_vddcore_level();
    SystemClock_Config_HSI_overdrive();
    fuse_vddio();

    CLEAR_BIT(SCB->SCR, SCB_SCR_SLEEPDEEP_Msk);

    printf("[INIT] Configuring UART...\n");
    UART_Config();
    /* From here on, printf is reliable at full baud rate. */

    printf("[INIT] Configuring NPU...\n");
    NPU_Config();
    RISAF_Config();
    set_clk_sleep_mode();

    printf("\n=== BirdNET-STM32 SD Card Inference ===\n");
    printf("[INFO] Sample rate: %d Hz, chunk: %ds, FFT: %d, hop: %d, "
           "spec: %dx%d, classes: %d\n",
           APP_SAMPLE_RATE, APP_CHUNK_DURATION, APP_FFT_LENGTH,
           APP_HOP_LENGTH, APP_FFT_BINS, APP_SPEC_WIDTH, APP_NUM_CLASSES);

    /* ---- NPU network init ---- */
    printf("[INIT] Initialising NPU network...\n");
    if (!LL_ATON_EC_Network_Init_Default()) {
        printf("[ERROR] NPU network init failed\n");
        while (1) {}
    }

    const LL_Buffer_InfoTypeDef *in_info  = LL_ATON_Input_Buffers_Info_Default();
    const LL_Buffer_InfoTypeDef *out_info = LL_ATON_Output_Buffers_Info_Default();
    if (in_info && in_info->name) {
        printf("[OK] NPU input:  \"%s\"  %lu bytes\n",
               in_info->name,
               (unsigned long)(in_info->offset_end - in_info->offset_start));
    }
    if (out_info && out_info->name) {
        printf("[OK] NPU output: \"%s\"  %lu bytes\n",
               out_info->name,
               (unsigned long)(out_info->offset_end - out_info->offset_start));
    }

    /* ---- Mount SD card ---- */
    printf("[INIT] Mounting SD card (SDMMC2)...\n");
    if (!sd_mount()) {
        printf("[ERROR] SD card mount failed\n");
        while (1) {}
    }
    printf("[OK] SD card mounted\n");

    /* ---- Labels ---- */
    printf("[OK] %d class labels compiled in\n", APP_NUM_CLASSES);

    /* ---- Scan audio directory ---- */
    printf("[INIT] Scanning /%s/ for .wav files...\n", APP_AUDIO_DIR);
    static SdFileList file_list;
    uint32_t num_files = sd_scan_audio_dir(APP_AUDIO_DIR, &file_list);
    printf("[OK] Found %lu audio files\n", (unsigned long)num_files);

    if (num_files == 0) {
        printf("[WARN] No .wav files found. Done.\n");
        printf("\n=== DONE ===\n");
        printf("Processed: 0 / 0 files (0 errors)\n");
        sd_unmount();
        while (1) {}
    }

    /* ---- Process each file ---- */
    float scores[APP_NUM_CLASSES];
    uint32_t processed = 0;
    uint32_t errors = 0;

    for (uint32_t i = 0; i < num_files; i++) {
        const char *filepath = file_list.paths[i];
        const char *basename = strrchr(filepath, '/');
        basename = basename ? basename + 1 : filepath;

        printf("\n[%lu/%lu] %s\n", (unsigned long)(i + 1),
               (unsigned long)num_files, basename);

        FIL fp;
        if (f_open(&fp, filepath, FA_READ) != FR_OK) {
            printf("  [SKIP] Cannot open file\n");
            errors++;
            continue;
        }

        WavInfo wav;
        if (!wav_parse_header(&fp, &wav)) {
            printf("  [SKIP] Invalid WAV format\n");
            f_close(&fp);
            errors++;
            continue;
        }

        printf("  [WAV] %lu Hz, %d-bit, %d ch, %lu samples\n",
               (unsigned long)wav.sample_rate, wav.bits_per_sample,
               wav.num_channels, (unsigned long)wav.num_samples);

        if (wav.sample_rate != APP_SAMPLE_RATE) {
            printf("  [SKIP] Sample rate %lu != %d\n",
                   (unsigned long)wav.sample_rate, APP_SAMPLE_RATE);
            f_close(&fp);
            errors++;
            continue;
        }

        /* Read first chunk */
        printf("  [READ] Loading %d samples (%ds)...\n",
               APP_CHUNK_SAMPLES, APP_CHUNK_DURATION);
        wav_read_chunk_f32(&fp, &wav, 0, APP_CHUNK_SAMPLES, audio_buf);
        f_close(&fp);

        /* Compute STFT on Cortex-M55 */
        printf("  [STFT] Computing %dx%d spectrogram...\n",
               APP_FFT_BINS, APP_SPEC_WIDTH);
        stft_magnitude(audio_buf, APP_CHUNK_SAMPLES,
                       APP_FFT_LENGTH, APP_HOP_LENGTH,
                       APP_SPEC_WIDTH, spec_buf);

        /* Run NPU inference */
        printf("  [NPU] Running inference...\n");
        if (!run_inference(spec_buf, scores)) {
            printf("  [ERROR] Inference failed\n");
            errors++;
            continue;
        }
        printf("  [OK] Inference complete\n");

        /* Print top-K results over UART */
        print_top_k(basename, scores, APP_TOP_K);
        processed++;
    }

    /* ---- Summary ---- */
    printf("\n=== DONE ===\n");
    printf("Processed: %lu / %lu files (%lu errors)\n",
           (unsigned long)processed, (unsigned long)num_files,
           (unsigned long)errors);

    sd_unmount();
    printf("[OK] SD card unmounted. Halting.\n");

    while (1) {
        /* Halt */
    }
}

void Error_Handler(void)
{
    while (1) {}
}
