"""Board test: standalone firmware on STM32N6570-DK.

Full on-device pipeline — nothing is precomputed on the host:
1. Deploy model: stedgeai generate → patch NPU_Validation project → n6_loader
   build + flash.
2. Firmware on board: read WAV from SD card → STFT on Cortex-M55 → NPU
   inference → results over UART.
3. This script captures UART output and parses per-file predictions.

Requires:
- USB-connected STM32N6570-DK with SD card containing audio/ and labels.txt.
- pyserial (pip install pyserial).
"""

import json
import logging
import os
import re
import shutil
import subprocess
import sys
import threading
import time
from dataclasses import dataclass, field
from pathlib import Path

import serial

from birdnet_stm32.deploy.config import DeployConfig
from birdnet_stm32.deploy.stedgeai import generate

log = logging.getLogger(__name__)

# NPU_Validation's misc_toolbox uses this baud rate (from its app_config.h).
UART_BAUDRATE = 921600

# Marker the firmware prints when all files have been processed.
DONE_MARKER = "=== DONE ==="

# Sentinel appended to the NPU_Validation Makefile so we can detect + remove
# our patch on cleanup.
MAKEFILE_SENTINEL = "# --- BirdNET-STM32 board test additions ---"

# hal_conf.h line to uncomment for SD card support.
HAL_SD_COMMENTED = "//#define HAL_SD_MODULE_ENABLED"
HAL_SD_UNCOMMENTED = "#define HAL_SD_MODULE_ENABLED"


# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

@dataclass
class BoardTestConfig:
    """Configuration for standalone on-board inference tests.

    Attributes:
        deploy_cfg: Base deployment configuration (paths to tools, model, etc.).
        model_config_path: Path to the _model_config.json file.
        labels_path: Path to the _labels.txt file.
        serial_port: Serial port for UART capture (e.g. /dev/ttyACM0).
        top_k: Number of top predictions to show per file.
        score_threshold: Minimum score to display.
        timeout: Maximum seconds to wait for firmware to finish.
    """

    deploy_cfg: DeployConfig = field(default_factory=DeployConfig)
    model_config_path: str = ""
    labels_path: str = ""
    serial_port: str = "/dev/ttyACM0"
    top_k: int = 5
    score_threshold: float = 0.01
    timeout: int = 300


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def load_model_config(config_path: str) -> dict:
    """Load model configuration from JSON.

    Args:
        config_path: Path to _model_config.json.

    Returns:
        Dict with model configuration.
    """
    with open(config_path) as f:
        return json.load(f)


def load_labels(labels_path: str) -> list[str]:
    """Load class labels from a labels.txt file.

    Args:
        labels_path: Path to _labels.txt (one label per line).

    Returns:
        List of label strings.
    """
    with open(labels_path) as f:
        return [line.strip() for line in f if line.strip()]


def _firmware_dir() -> Path:
    """Return the path to the firmware/ directory shipped with this package."""
    return Path(__file__).resolve().parent.parent.parent / "firmware"


def _generate_app_labels_h(labels: list[str]) -> str:
    """Generate the contents of ``app_labels.h`` from a list of class labels.

    Args:
        labels: Ordered class label strings (one per output neuron).

    Returns:
        C header source as a string.
    """
    n = len(labels)
    lines = [
        "/* Auto-generated by board_test.py — do not edit. */",
        "#ifndef APP_LABELS_H",
        "#define APP_LABELS_H",
        "",
        f"#define APP_NUM_CLASSES_ACTUAL {n}",
        "",
        "static const char * const APP_LABELS[] = {",
    ]
    for label in labels:
        escaped = label.replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'    "{escaped}",')
    lines += [
        "};",
        "",
        "#endif /* APP_LABELS_H */",
        "",
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Project patching — copies firmware sources into NPU_Validation tree
# ---------------------------------------------------------------------------

def _resolve_project_path(cfg: DeployConfig) -> Path:
    """Read the NPU_Validation project path from the n6_loader config."""
    with open(cfg.n6_loader_config) as f:
        n6cfg = json.load(f)
    return Path(n6cfg["project_path"])


def _backup(path: Path) -> Path:
    """Create a .bak copy of *path* if it exists.  Returns the backup path."""
    bak = path.with_suffix(path.suffix + ".bak")
    if path.exists():
        shutil.copy2(path, bak)
    return bak


def _restore(bak: Path) -> None:
    """Restore original from a .bak file and remove the backup."""
    orig = Path(str(bak).removesuffix(".bak"))
    if bak.exists():
        shutil.move(str(bak), str(orig))
    elif orig.exists():
        # New file we added — remove it.
        orig.unlink()


def patch_project(
    project: Path,
    model_cfg: dict,
    num_classes: int,
    labels: list[str],
) -> list[Path]:
    """Copy firmware sources into the NPU_Validation project and patch build files.

    Args:
        project: Path to the NPU_Validation project root.
        model_cfg: Model configuration dict from _model_config.json.
        num_classes: Number of output classes.
        labels: Ordered list of class label strings.  If empty, generates
                placeholder ``class_0`` … ``class_N`` labels.

    Returns a list of .bak paths that must be passed to ``restore_project``.
    """
    fw = _firmware_dir()
    core_src = project / "Core" / "Src"
    core_inc = project / "Core" / "Inc"
    hal_src = project / "Drivers" / "STM32N6xx_HAL_Driver" / "Src"
    bsp_dk = project / "Drivers" / "BSP" / "STM32N6570-DK"
    fatfs_dst = project / "FatFs"
    makefile = project / "armgcc" / "Makefile"
    hal_conf = core_inc / "stm32n6xx_hal_conf.h"
    app_conf = core_inc / "app_config.h"

    backups: list[Path] = []

    # --- 1. Copy firmware C sources into Core/Src --------------------------
    for name in ("main.c", "wav_reader.c", "audio_stft.c", "sd_handler.c", "fft.c"):
        dst = core_src / name
        backups.append(_backup(dst))
        shutil.copy2(fw / "Src" / name, dst)

    # --- 2. Copy firmware headers into Core/Inc ----------------------------
    #  Skip app_config.h — we patch the NPU_Validation original in step 6.
    for name in ("wav_reader.h", "audio_stft.h", "sd_handler.h", "fft.h"):
        dst = core_inc / name
        backups.append(_backup(dst))
        shutil.copy2(fw / "Inc" / name, dst)

    # FatFs config headers also go to Core/Inc (already in include path).
    for name in ("ffconf.h", "sd_diskio_config.h"):
        dst = core_inc / name
        backups.append(_backup(dst))
        shutil.copy2(fw / "Config" / name, dst)

    # --- 2b. Generate app_labels.h from the model's label list -------------
    if not labels:
        labels = [f"class_{i}" for i in range(num_classes)]
    app_labels_dst = core_inc / "app_labels.h"
    backups.append(_backup(app_labels_dst))
    app_labels_dst.write_text(_generate_app_labels_h(labels))
    log.info("Generated app_labels.h with %d labels", len(labels))

    # --- 3. Copy HAL SD driver sources and headers --------------------------
    hal_inc = project / "Drivers" / "STM32N6xx_HAL_Driver" / "Inc"
    for name in ("stm32n6xx_hal_sd.c", "stm32n6xx_ll_sdmmc.c"):
        dst = hal_src / name
        backups.append(_backup(dst))
        shutil.copy2(fw / "Drivers" / "HAL_SD" / name, dst)
    for name in ("stm32n6xx_hal_sd.h", "stm32n6xx_hal_sd_ex.h",
                 "stm32n6xx_ll_sdmmc.h", "stm32n6xx_ll_dlyb.h"):
        dst = hal_inc / name
        backups.append(_backup(dst))
        shutil.copy2(fw / "Drivers" / "HAL_SD" / name, dst)

    # --- 4. Copy BSP SD driver ---------------------------------------------
    for name in ("stm32n6570_discovery_sd.c", "stm32n6570_discovery_sd.h"):
        dst = bsp_dk / name
        backups.append(_backup(dst))
        shutil.copy2(fw / "Drivers" / name, dst)

    # --- 5. Copy FatFs middleware -------------------------------------------
    fatfs_dst.mkdir(exist_ok=True)
    backups.append(fatfs_dst)  # entire dir — removed on cleanup
    for p in (fw / "Drivers" / "FatFs").iterdir():
        if p.is_file():
            shutil.copy2(p, fatfs_dst / p.name)

    # --- 6. Patch app_config.h — append our defines to existing file -------
    #  The NPU_Validation app_config.h has USE_OVERDRIVE, USE_UART_BAUDRATE,
    #  etc.  We append our audio/inference defines from model_config.json
    #  before its closing #endif guard.
    backups.append(_backup(app_conf))
    _patch_app_config(app_conf, model_cfg, num_classes)

    # --- 7. Patch hal_conf.h — enable HAL_SD module ------------------------
    backups.append(_backup(hal_conf))
    text = hal_conf.read_text()
    if HAL_SD_COMMENTED in text:
        hal_conf.write_text(text.replace(HAL_SD_COMMENTED, HAL_SD_UNCOMMENTED))
        log.info("Enabled HAL_SD_MODULE in hal_conf.h")

    # --- 8. Patch Makefile — add our sources and include paths -------------
    backups.append(_backup(makefile))
    _patch_makefile(makefile)

    log.info("Project patched (%d backups created)", len(backups))
    return backups


def _patch_app_config(path: Path, model_cfg: dict, num_classes: int) -> None:
    """Append BirdNET audio/inference defines to the NPU_Validation app_config.h."""
    sr = model_cfg["sample_rate"]
    chunk = model_cfg["chunk_duration"]
    fft_len = model_cfg["fft_length"]
    hop = model_cfg.get("hop_length", fft_len // 2 + 2)
    sw = model_cfg["spec_width"]

    block = f"""
/* --- BirdNET-STM32 board test parameters (auto-generated) --- */
#define APP_SAMPLE_RATE       {sr}
#define APP_CHUNK_DURATION    {chunk}
#define APP_CHUNK_SAMPLES     (APP_SAMPLE_RATE * APP_CHUNK_DURATION)
#define APP_FFT_LENGTH        {fft_len}
#define APP_FFT_BINS          (APP_FFT_LENGTH / 2 + 1)
#define APP_HOP_LENGTH        {hop}
#define APP_SPEC_WIDTH        {sw}
#define APP_NUM_CLASSES       {num_classes}
#define APP_AUDIO_DIR         "audio"
#define APP_RESULTS_FILE      "results.txt"
#define APP_TOP_K             5
#define APP_SCORE_THRESHOLD   0.01f
/* --- end BirdNET parameters --- */
"""
    text = path.read_text()
    # Insert before the closing #endif of the NPU_Validation guard.
    text = text.replace(
        "#endif /* __APP_CONFIG_H__ */",
        block + "\n#endif /* __APP_CONFIG_H__ */",
    )
    path.write_text(text)
    log.info("Patched app_config.h with model parameters")


MAKEFILE_END_SENTINEL = "# --- end BirdNET-STM32 additions ---"


def _patch_makefile(path: Path) -> None:
    """Insert BirdNET sources before the OBJECTS definition in the Makefile."""
    text = path.read_text()
    # Strip any leftover patch block (e.g. from a corrupted .bak restore).
    if MAKEFILE_SENTINEL in text:
        start = text.find(MAKEFILE_SENTINEL)
        end = text.find(MAKEFILE_END_SENTINEL)
        if start != -1 and end != -1:
            # Remove from the start of the sentinel line to end of end-marker line.
            line_start = text.rfind("\n", 0, start)
            line_start = 0 if line_start == -1 else line_start
            line_end = text.find("\n", end)
            line_end = len(text) if line_end == -1 else line_end + 1
            text = text[:line_start] + text[line_end:]
            log.info("Stripped leftover Makefile patch block")
        else:
            log.info("Makefile already patched — skipping")
            return

    addition = f"""\
{MAKEFILE_SENTINEL}
FATFS_PATH = $(PROJECT_PATH)/FatFs
DRIVER_SOURCES += $(N6_DRIVER_PATH)/Src/stm32n6xx_hal_sd.c
DRIVER_SOURCES += $(N6_DRIVER_PATH)/Src/stm32n6xx_ll_sdmmc.c
DRIVER_SOURCES += $(DK_DRIVER_PATH)/stm32n6570_discovery_sd.c
C_SOURCES += $(CORE_PATH)/Src/wav_reader.c
C_SOURCES += $(CORE_PATH)/Src/audio_stft.c
C_SOURCES += $(CORE_PATH)/Src/sd_handler.c
C_SOURCES += $(CORE_PATH)/Src/fft.c
C_SOURCES += $(FATFS_PATH)/ff.c
C_SOURCES += $(FATFS_PATH)/diskio.c
C_SOURCES += $(FATFS_PATH)/ff_gen_drv.c
C_SOURCES += $(FATFS_PATH)/sd_diskio.c
C_INCLUDES += -I$(FATFS_PATH)
{MAKEFILE_END_SENTINEL}
"""
    # Insert before OBJECTS definition so pattern substitution picks up our sources.
    # The OBJECTS line uses $(C_SOURCES:...) pattern substitution.
    marker = "OBJECTS = $(C_SOURCES:"
    idx = text.find(marker)
    if idx == -1:
        # Fallback: append to end.
        text += "\n" + addition
    else:
        # Insert just before the OBJECTS line.
        line_start = text.rfind("\n", 0, idx)
        if line_start == -1:
            line_start = 0
        else:
            line_start += 1
        text = text[:line_start] + addition + "\n" + text[line_start:]
    path.write_text(text)
    log.info("Patched Makefile with BirdNET sources")


def restore_project(backups: list[Path]) -> None:
    """Undo all project patches by restoring .bak files and removing new files.

    For each entry in *backups*:
    - If it is a directory (FatFs), remove it entirely.
    - If it is a ``.bak`` path and the .bak exists, move it back over the original.
    - If it is a ``.bak`` path but no .bak was created (file was new), delete
      the original that we copied in.
    """
    for entry in reversed(backups):
        if entry.is_dir() and entry.suffix != ".bak":
            shutil.rmtree(entry, ignore_errors=True)
        else:
            _restore(entry)
    log.info("Project restored")


# ---------------------------------------------------------------------------
# Serial capture
# ---------------------------------------------------------------------------

def _serial_capture(
    port: str,
    baudrate: int,
    lines: list[str],
    done: threading.Event,
    timeout: float,
) -> None:
    """Background thread: read UART lines until DONE marker or timeout.

    Handles board resets (port disconnection) by retrying the connection.
    """
    deadline = time.monotonic() + timeout
    ser = None

    while not done.is_set() and time.monotonic() < deadline:
        # (Re-)open the serial port if needed.
        if ser is None:
            try:
                ser = serial.Serial(port, baudrate, timeout=1)
            except serial.SerialException:
                time.sleep(0.5)
                continue

        try:
            raw = ser.readline()
        except serial.SerialException:
            # Port disconnected (board reset during flash).
            ser.close()
            ser = None
            continue

        if not raw:
            continue
        line = raw.decode("utf-8", errors="replace").rstrip("\r\n")
        lines.append(line)
        if DONE_MARKER in line:
            done.set()
            # Read the summary line that follows.
            try:
                extra = ser.readline()
                if extra:
                    lines.append(extra.decode("utf-8", errors="replace").rstrip("\r\n"))
            except serial.SerialException:
                pass
            break

    if ser is not None:
        ser.close()


# ---------------------------------------------------------------------------
# Serial output parser
# ---------------------------------------------------------------------------

# Example firmware output:
#   [1/10] song_sparrow_01.wav
#     [1] Melospiza melodia_Song Sparrow: 87.3%
#     [2] Passerella iliaca_Fox Sparrow: 4.1%
_RE_FILE = re.compile(r"^\[(\d+)/(\d+)\]\s+(.+)$")
_RE_DET = re.compile(r"^\s+\[(\d+)\]\s+(.+?):\s+([\d.]+)%$")
_RE_SUMMARY = re.compile(r"^Processed:\s+(\d+)\s*/\s*(\d+)\s+files\s+\((\d+)\s+errors\)")


def parse_serial_output(
    lines: list[str],
    labels: list[str],
    top_k: int = 5,
    threshold: float = 0.01,
) -> dict:
    """Parse firmware UART output into structured results.

    Args:
        lines: Raw serial lines captured from the board.
        labels: Class label list (for reference; firmware already prints names).
        top_k: Max detections per file to keep.
        threshold: Minimum score fraction (0–1) to include.

    Returns:
        Dict with 'results' (list of per-file dicts), 'processed', 'errors',
        'raw_lines'.
    """
    results: list[dict] = []
    current_file: dict | None = None
    processed = 0
    total = 0
    errors = 0

    for line in lines:
        m = _RE_FILE.match(line)
        if m:
            if current_file is not None:
                results.append(current_file)
            current_file = {
                "file": m.group(3),
                "detections": [],
            }
            continue

        m = _RE_DET.match(line)
        if m and current_file is not None:
            score = float(m.group(3)) / 100.0
            if score >= threshold and len(current_file["detections"]) < top_k:
                current_file["detections"].append({
                    "label": m.group(2),
                    "score": score,
                })
            continue

        m = _RE_SUMMARY.match(line)
        if m:
            processed = int(m.group(1))
            total = int(m.group(2))
            errors = int(m.group(3))

    if current_file is not None:
        results.append(current_file)

    return {
        "results": results,
        "processed": processed,
        "total": total,
        "errors": errors,
        "raw_lines": lines,
    }


# ---------------------------------------------------------------------------
# Main entry
# ---------------------------------------------------------------------------

def run_board_test(cfg: BoardTestConfig) -> dict:
    """Execute the full on-board inference test.

    Steps:
    1. stedgeai generate → produce NPU binary from the TFLite model.
    2. Patch NPU_Validation project with our firmware sources.
    3. n6_loader: copy network.c, build firmware, flash, run.
    4. Capture UART output until '=== DONE ===' marker.
    5. Restore the NPU_Validation project to its original state.
    6. Parse and report results.

    Args:
        cfg: Board test configuration.

    Returns:
        Dict with 'results', 'processed', 'errors', 'raw_lines', 'labels'.
    """
    deploy = cfg.deploy_cfg

    # --- Validate prerequisites ---
    if not os.path.isfile(deploy.model_path):
        print(f"[ERROR] Model not found: {deploy.model_path}")
        sys.exit(1)
    if not os.path.isfile(deploy.stedgeai_path):
        print(f"[ERROR] stedgeai not found: {deploy.stedgeai_path}")
        sys.exit(1)
    if not os.path.isfile(cfg.model_config_path):
        print(f"[ERROR] Model config not found: {cfg.model_config_path}")
        sys.exit(1)
    if not os.path.isfile(deploy.n6_loader_script):
        print(f"[ERROR] n6_loader.py not found: {deploy.n6_loader_script}")
        sys.exit(1)
    if not os.path.isfile(deploy.n6_loader_config):
        print(f"[ERROR] n6_loader config not found: {deploy.n6_loader_config}")
        sys.exit(1)

    model_cfg = load_model_config(cfg.model_config_path)
    labels = load_labels(cfg.labels_path) if cfg.labels_path else []
    num_classes = len(labels) if labels else model_cfg.get("num_classes", 1000)

    print("\n=== BirdNET-STM32 Board Test (standalone firmware) ===\n")
    print(f"  Model:       {deploy.model_path}")
    print(f"  Config:      {cfg.model_config_path}")
    print(f"  Labels:      {cfg.labels_path or '(none)'} ({num_classes} classes)")
    print(f"  Serial port: {cfg.serial_port}")
    print(f"  Timeout:     {cfg.timeout}s")
    print()

    project = _resolve_project_path(deploy)

    # Step 1: stedgeai generate
    print("--- Step 1: Generate NPU binary (stedgeai generate) ---")
    generate(deploy)

    # Step 2: Patch the NPU_Validation project
    print("\n--- Step 2: Patch NPU_Validation project ---")
    backups = patch_project(project, model_cfg, num_classes, labels)

    try:
        # Step 3: Start serial capture (before n6_loader starts the firmware)
        print("\n--- Step 3: Build, flash, and run ---")
        serial_lines: list[str] = []
        done_event = threading.Event()
        serial_thread = threading.Thread(
            target=_serial_capture,
            args=(cfg.serial_port, UART_BAUDRATE, serial_lines, done_event, cfg.timeout),
            daemon=True,
        )
        serial_thread.start()

        # Step 4: n6_loader — copies network.c, builds, flashes, runs firmware
        n6_cmd = [
            sys.executable,
            deploy.n6_loader_script,
            "--n6-loader-config", deploy.n6_loader_config,
            "--clean",
        ]
        print(f"  $ {' '.join(n6_cmd)}")
        result = subprocess.run(n6_cmd, check=False)
        if result.returncode != 0:
            print(f"[ERROR] n6_loader failed (exit code {result.returncode})")
            sys.exit(result.returncode)

        # Wait for firmware to finish (or timeout)
        print("\n--- Step 4: Waiting for firmware output ---")
        if not done_event.is_set():
            done_event.wait(timeout=cfg.timeout)
        serial_thread.join(timeout=5)

        if not done_event.is_set():
            print(f"[WARN] Timeout after {cfg.timeout}s — firmware may not have finished")

    finally:
        # Step 5: Restore original project files
        print("\n--- Step 5: Restore NPU_Validation project ---")
        restore_project(backups)

    # Step 6: Parse and display results
    print("\n--- Results ---")
    parsed = parse_serial_output(serial_lines, labels, cfg.top_k, cfg.score_threshold)

    for r in parsed["results"]:
        det_str = ", ".join(
            f"{d['label']} ({d['score']:.1%})" for d in r["detections"]
        )
        print(f"\n  {r['file']}")
        if det_str:
            print(f"    {det_str}")
        else:
            print("    (no detections above threshold)")

    print(f"\n=== DONE: {parsed['processed']}/{parsed['total']} files "
          f"({parsed['errors']} errors) ===")

    parsed["labels"] = labels
    return parsed
