/* Auto-generated by gen_app_config.py — do not edit.
 *
 * Source: model_config.json
 * Target: STM32N6570-DK  (Cortex-M55 + NPU)
 */

#ifndef APP_CONFIG_H
#define APP_CONFIG_H

/* --- NPU_Validation board support defines --------------------------------- */
/* These are required by misc_toolbox.c / system_clock_config.c from the       */
/* NPU_Validation project when building inside that tree.                      */
#ifndef NUCLEO_N6_CONFIG
#define NUCLEO_N6_CONFIG                0
#endif
#ifndef USE_MCU_DCACHE
#define USE_MCU_DCACHE                  1
#endif
#ifndef USE_MCU_ICACHE
#define USE_MCU_ICACHE                  1
#endif
#ifndef USE_EXTERNAL_MEMORY_DEVICES
#define USE_EXTERNAL_MEMORY_DEVICES     1
#endif

/* --- Audio parameters (from model_config.json) ---------------------------- */
#define APP_SAMPLE_RATE       22050
#define APP_CHUNK_DURATION    2.9
#define APP_CHUNK_SAMPLES     63945
#define APP_FFT_LENGTH        512
#define APP_FFT_BINS          (APP_FFT_LENGTH / 2 + 1)
#define APP_HOP_LENGTH        172
#define APP_SPEC_WIDTH        256
#define APP_NUM_MELS          64
#define APP_NUM_CLASSES       10

/* --- Audio frontend mode -------------------------------------------------- */
/* 0 = hybrid:      STFT on M55 → feed [fft_bins, spec_width] to NPU         */
/* 1 = raw:         feed raw waveform [chunk_samples, 1] to NPU (no STFT)    */
/* 2 = precomputed: STFT + mel filterbank on M55 → feed [num_mels, spec_width] */
#define APP_FRONTEND_HYBRID       0
#define APP_FRONTEND_RAW          1
#define APP_FRONTEND_PRECOMPUTED  2
#define APP_AUDIO_FRONTEND        APP_FRONTEND_RAW

/* --- SD card paths -------------------------------------------------------- */
#define APP_AUDIO_DIR         "audio"
#define APP_RESULTS_FILE      "results.txt"

/* --- Inference ------------------------------------------------------------- */
#define APP_TOP_K             5
#define APP_SCORE_THRESHOLD   0.01f

#endif /* APP_CONFIG_H */
