/* Auto-generated — do not edit. */
#ifndef APP_LABELS_H
#define APP_LABELS_H

#define APP_NUM_CLASSES_ACTUAL 1000

static const char * const APP_LABELS[] = {
    "Abroscopus superciliaris_Yellow-bellied Warbler",
    "Acanthagenys rufogularis_Spiny-cheeked Honeyeater",
    "Acanthiza chrysorrhoa_Yellow-rumped Thornbill",
    "Acanthiza lineata_Striated Thornbill",
    "Acanthiza nana_Yellow Thornbill",
    "Acanthiza pusilla_Brown Thornbill",
    "Acanthiza reguloides_Buff-rumped Thornbill",
    "Acanthorhynchus tenuirostris_Eastern Spinebill",
    "Accipiter cooperii_Cooper's Hawk",
    "Accipiter fasciatus_Brown Goshawk",
    "Accipiter gentilis_Northern Goshawk",
    "Accipiter nisus_Eurasian Sparrowhawk",
    "Accipiter striatus_Sharp-shinned Hawk",
    "Acridotheres javanicus_Javan Myna",
    "Acridotheres tristis_Common Myna",
    "Acrocephalus arundinaceus_Great Reed Warbler",
    "Acrocephalus australis_Australian Reed Warbler",
    "Acrocephalus palustris_Marsh Warbler",
    "Acrocephalus rufescens_Greater Swamp Warbler",
    "Acrocephalus schoenobaenus_Sedge Warbler",
    "Acrocephalus scirpaceus_Eurasian Reed Warbler",
    "Actenoides concretus_Rufous-collared Kingfisher",
    "Actitis hypoleucos_Common Sandpiper",
    "Actitis macularius_Spotted Sandpiper",
    "Actophilornis africanus_African Jacana",
    "Aechmophorus clarkii_Clark's Grebe",
    "Aechmophorus occidentalis_Western Grebe",
    "Aegithalos caudatus_Long-tailed Tit",
    "Aerodramus fuciphagus_White-nest Swiftlet",
    "Aeronautes saxatalis_White-throated Swift",
    "Aethopyga siparaja_Crimson Sunbird",
    "Aethopyga temminckii_Temminck's Sunbird",
    "Agelaius phoeniceus_Red-winged Blackbird",
    "Aix sponsa_Wood Duck",
    "Alauda arvensis_Eurasian Skylark",
    "Alcedo atthis_Common Kingfisher",
    "Alcippe brunneicauda_Brown Fulvetta",
    "Alisterus scapularis_Australian King-Parrot",
    "Alophoixus tephrogenys_Gray-cheeked Bulbul",
    "Alopochen aegyptiaca_Egyptian Goose",
    "Amaurornis phoenicurus_White-breasted Waterhen",
    "Amazilia rutila_Cinnamon Hummingbird",
    "Amazilia tzacatl_Rufous-tailed Hummingbird",
    "Amazilia yucatanensis_Buff-bellied Hummingbird",
    "Amazona albifrons_White-fronted Parrot",
    "Amazona amazonica_Orange-winged Parrot",
    "Amazona autumnalis_Red-lored Parrot",
    "Amazona kawalli_Kawall's Parrot",
    "Amblycercus holosericeus_Yellow-billed Cacique",
    "Amphispiza bilineata_Black-throated Sparrow",
    "Anas acuta_Northern Pintail",
    "Anas castanea_Chestnut Teal",
    "Anas crecca_Green-winged Teal",
    "Anas gracilis_Gray Teal",
    "Anas platyrhynchos_Mallard",
    "Anas rubripes_American Black Duck",
    "Anas superciliosa_Pacific Black Duck",
    "Anhinga novaehollandiae_Australasian Darter",
    "Anser albifrons_Greater White-fronted Goose",
    "Anser anser_Graylag Goose",
    "Anser caerulescens_Snow Goose",
    "Anser serrirostris_Tundra Bean-Goose",
    "Anthochaera carunculata_Red Wattlebird",
    "Anthochaera chrysoptera_Little Wattlebird",
    "Anthreptes malacensis_Brown-throated Sunbird",
    "Anthus novaeseelandiae_Australasian Pipit",
    "Anthus pratensis_Meadow Pipit",
    "Anthus rubescens_American Pipit",
    "Anthus spinoletta_Water Pipit",
    "Anthus trivialis_Tree Pipit",
    "Antigone canadensis_Sandhill Crane",
    "Aphelocoma californica_California Scrub-Jay",
    "Aplonis panayensis_Asian Glossy Starling",
    "Apus affinis_Little Swift",
    "Apus apus_Common Swift",
    "Aquila chrysaetos_Golden Eagle",
    "Ara ararauna_Blue-and-yellow Macaw",
    "Ara severus_Chestnut-fronted Macaw",
    "Arachnothera chrysogenys_Yellow-eared Spiderhunter",
    "Arachnothera crassirostris_Thick-billed Spiderhunter",
    "Arachnothera flavigaster_Spectacled Spiderhunter",
    "Arachnothera longirostra_Little Spiderhunter",
    "Aramides albiventris_Russet-naped Wood-Rail",
    "Aratinga weddellii_Dusky-headed Parakeet",
    "Archilochus alexandri_Black-chinned Hummingbird",
    "Archilochus colubris_Ruby-throated Hummingbird",
    "Ardea alba_Great Egret",
    "Ardea cinerea_Gray Heron",
    "Ardea cocoi_Cocoi Heron",
    "Ardea herodias_Great Blue Heron",
    "Ardea intermedia_Intermediate Egret",
    "Ardea melanocephala_Black-headed Heron",
    "Arenaria interpres_Ruddy Turnstone",
    "Arremon taciturnus_Pectoral Sparrow",
    "Arremonops chloronotus_Green-backed Sparrow",
    "Artamus cyanopterus_Dusky Woodswallow",
    "Artamus leucorynchus_White-breasted Woodswallow",
    "Atimastillas flavicollis_Yellow-throated Greenbul",
    "Attila bolivianus_Dull-capped Attila",
    "Attila spadiceus_Bright-rumped Attila",
    "Auriparus flaviceps_Verdin",
    "Automolus paraensis_Para Foliage-gleaner",
    "Aythya affinis_Lesser Scaup",
    "Aythya americana_Redhead",
    "Aythya collaris_Ring-necked Duck",
    "Aythya ferina_Common Pochard",
    "Aythya fuligula_Tufted Duck",
    "Aythya valisineria_Canvasback",
    "Baeolophus bicolor_Tufted Titmouse",
    "Baeopogon indicator_Honeyguide Greenbul",
    "Bathmocercus rufus_Black-faced Rufous-Warbler",
    "Batis molitor_Chinspot Batis",
    "Batrachostomus auritus_Large Frogmouth",
    "Batrachostomus cornutus_Sunda Frogmouth",
    "Batrachostomus stellatus_Gould's Frogmouth",
    "Berenicornis comatus_White-crowned Hornbill",
    "Bias musicus_Black-and-white Shrike-flycatcher",
    "Biziura lobata_Musk Duck",
    "Bleda notatus_Lesser Bristlebill",
    "Blythipicus rubiginosus_Maroon Woodpecker",
    "Bombycilla cedrorum_Cedar Waxwing",
    "Bostrychia hagedash_Hadada Ibis",
    "Brachypodius eutilotus_Puff-backed Bulbul",
    "Brachypodius melanoleucos_Black-and-white Bulbul",
    "Branta canadensis_Canada Goose",
    "Brotogeris chiriri_Yellow-chevroned Parakeet",
    "Bubo sumatranus_Barred Eagle-Owl",
    "Bubo virginianus_Great Horned Owl",
    "Bubulcus ibis_Cattle Egret",
    "Buccanodon duchaillui_Yellow-spotted Barbet",
    "Bucco tamatia_Spotted Puffbird",
    "Bucephala albeola_Bufflehead",
    "Bucephala clangula_Common Goldeneye",
    "Buteo buteo_Common Buzzard",
    "Buteo jamaicensis_Red-tailed Hawk",
    "Buteo lineatus_Red-shouldered Hawk",
    "Buteo plagiatus_Gray Hawk",
    "Buteo platypterus_Broad-winged Hawk",
    "Buteo regalis_Ferruginous Hawk",
    "Butorides striata_Striated Heron",
    "Butorides virescens_Green Heron",
    "Bycanistes fistulator_Piping Hornbill",
    "Bycanistes subcylindricus_Black-and-white-casqued Hornbill",
    "Cacatua galerita_Sulphur-crested Cockatoo",
    "Cacatua sanguinea_Little Corella",
    "Cacicus cela_Yellow-rumped Cacique",
    "Cacomantis flabelliformis_Fan-tailed Cuckoo",
    "Calidris acuminata_Sharp-tailed Sandpiper",
    "Calidris alba_Sanderling",
    "Calidris alpina_Dunlin",
    "Calidris mauri_Western Sandpiper",
    "Calidris minutilla_Least Sandpiper",
    "Calidris pugnax_Ruff",
    "Calidris pusilla_Semipalmated Sandpiper",
    "Calidris ruficollis_Red-necked Stint",
    "Caligavis chrysops_Yellow-faced Honeyeater",
    "Callipepla californica_California Quail",
    "Caloramphus fuliginosus_Brown Barbet",
    "Calypte anna_Anna's Hummingbird",
    "Calypte costae_Costa's Hummingbird",
    "Calyptomena viridis_Green Broadbill",
    "Calyptorhynchus funereus_Yellow-tailed Black-Cockatoo",
    "Camaroptera brachyura_Green-backed Camaroptera",
    "Camaroptera chloronota_Olive-green Camaroptera",
    "Camaroptera superciliaris_Yellow-browed Camaroptera",
    "Campephilus guatemalensis_Pale-billed Woodpecker",
    "Campephilus rubricollis_Red-necked Woodpecker",
    "Camptostoma obsoletum_Southern Beardless-Tyrannulet",
    "Campylorhamphus procurvoides_Curve-billed Scythebill",
    "Capito dayi_Black-girdled Barbet",
    "Caprimulgus climacurus_Long-tailed Nightjar",
    "Caprimulgus natalensis_Swamp Nightjar",
    "Caracara plancus_Crested Caracara",
    "Cardellina canadensis_Canada Warbler",
    "Cardellina pusilla_Wilson's Warbler",
    "Cardinalis cardinalis_Northern Cardinal",
    "Carduelis carduelis_European Goldfinch",
    "Cathartes aura_Turkey Vulture",
    "Catharus fuscescens_Veery",
    "Catharus guttatus_Hermit Thrush",
    "Catharus ustulatus_Swainson's Thrush",
    "Catherpes mexicanus_Canyon Wren",
    "Cecropis cucullata_Greater Striped Swallow",
    "Cecropis semirufa_Rufous-chested Swallow",
    "Celeus flavus_Cream-colored Woodpecker",
    "Centropus rectunguis_Short-toed Coucal",
    "Centropus senegalensis_Senegal Coucal",
    "Centropus sinensis_Greater Coucal",
    "Centropus superciliosus_White-browed Coucal",
    "Ceratopipra rubrocapilla_Red-headed Manakin",
    "Cercococcyx mechowi_Dusky Long-tailed Cuckoo",
    "Cercococcyx olivinus_Olive Long-tailed Cuckoo",
    "Cercomacra cinerascens_Gray Antbird",
    "Cercomacra ferdinandi_Bananal Antbird",
    "Certhia americana_Brown Creeper",
    "Certhia brachydactyla_Short-toed Treecreeper",
    "Certhia familiaris_Eurasian Treecreeper",
    "Chaetura chapmani_Chapman's Swift",
    "Chaetura pelagica_Chimney Swift",
    "Chaetura vauxi_Vaux's Swift",
    "Chalcomitra amethystina_Amethyst Sunbird",
    "Chalcoparia singalensis_Ruby-cheeked Sunbird",
    "Charadrius dubius_Little Ringed Plover",
    "Charadrius semipalmatus_Semipalmated Plover",
    "Charadrius vociferus_Killdeer",
    "Chenonetta jubata_Maned Duck",
    "Chionomesa fimbriata_Glittering-throated Emerald",
    "Chlorestes candida_White-bellied Emerald",
    "Chloris chloris_European Greenfinch",
    "Chloroceryle inda_Green-and-rufous Kingfisher",
    "Chlorocichla simplex_Simple Greenbul",
    "Chloropicus fuscescens_Cardinal Woodpecker",
    "Chloropsis cochinchinensis_Blue-winged Leafbird",
    "Chloropsis cyanopogon_Lesser Green Leafbird",
    "Chloropsis sonnerati_Greater Green Leafbird",
    "Chondestes grammacus_Lark Sparrow",
    "Chroicocephalus novaehollandiae_Silver Gull",
    "Chroicocephalus ridibundus_Black-headed Gull",
    "Chrysococcyx caprius_Dideric Cuckoo",
    "Chrysococcyx cupreus_African Emerald Cuckoo",
    "Chrysococcyx klaas_Klaas's Cuckoo",
    "Chrysococcyx lucidus_Shining Bronze-Cuckoo",
    "Chrysophlegma mentale_Checker-throated Woodpecker",
    "Ciconia ciconia_White Stork",
    "Cincloramphus mathewsi_Rufous Songlark",
    "Cinnyris coccinigastrus_Splendid Sunbird",
    "Cinnyris jugularis_Olive-backed Sunbird",
    "Cinnyris venustus_Variable Sunbird",
    "Circus aeruginosus_Eurasian Marsh-Harrier",
    "Circus hudsonius_Northern Harrier",
    "Cissa chinensis_Common Green-Magpie",
    "Cisticola anonymus_Chattering Cisticola",
    "Cisticola exilis_Golden-headed Cisticola",
    "Cisticola fulvicapilla_Piping Cisticola",
    "Cistothorus palustris_Marsh Wren",
    "Clamator levaillantii_Levaillant's Cuckoo",
    "Climacteris picumnus_Brown Treecreeper",
    "Coccothraustes coccothraustes_Hawfinch",
    "Coccyzus americanus_Yellow-billed Cuckoo",
    "Coereba flaveola_Bananaquit",
    "Colaptes auratus_Northern Flicker",
    "Colinus nigrogularis_Black-throated Bobwhite",
    "Colius striatus_Speckled Mousebird",
    "Collocalia affinis_Plume-toed Swiftlet",
    "Colluricincla harmonica_Gray Shrikethrush",
    "Columba livia_Rock Pigeon",
    "Columba oenas_Stock Dove",
    "Columba palumbus_Common Wood-Pigeon",
    "Columbina picui_Picui Ground Dove",
    "Columbina squammata_Scaled Dove",
    "Columbina talpacoti_Ruddy Ground Dove",
    "Contopus sordidulus_Western Wood-Pewee",
    "Contopus virens_Eastern Wood-Pewee",
    "Copsychus malabaricus_White-rumped Shama",
    "Copsychus saularis_Oriental Magpie-Robin",
    "Coracias caudatus_Lilac-breasted Roller",
    "Coracina novaehollandiae_Black-faced Cuckooshrike",
    "Coragyps atratus_Black Vulture",
    "Corcorax melanorhamphos_White-winged Chough",
    "Cormobates leucophaea_White-throated Treecreeper",
    "Corthylio calendula_Ruby-crowned Kinglet",
    "Corvus albus_Pied Crow",
    "Corvus brachyrhynchos_American Crow",
    "Corvus corax_Common Raven",
    "Corvus cornix_Hooded Crow",
    "Corvus corone_Carrion Crow",
    "Corvus coronoides_Australian Raven",
    "Corvus enca_Slender-billed Crow",
    "Corvus frugilegus_Rook",
    "Corvus mellori_Little Raven",
    "Corvus monedula_Eurasian Jackdaw",
    "Corvus orru_Torresian Crow",
    "Corydon sumatranus_Dusky Broadbill",
    "Corythaeola cristata_Great Blue Turaco",
    "Corythornis cristatus_Malachite Kingfisher",
    "Cossypha cyanocampter_Blue-shouldered Robin-Chat",
    "Cracticus nigrogularis_Pied Butcherbird",
    "Cracticus torquatus_Gray Butcherbird",
    "Cranioleuca gutturata_Speckled Spinetail",
    "Crax fasciolata_Bare-faced Curassow",
    "Crinifer piscator_Western Plantain-eater",
    "Criniger chloronotus_Eastern Bearded-Greenbul",
    "Crithagra atrogularis_Black-throated Canary",
    "Crotophaga ani_Smooth-billed Ani",
    "Crotophaga sulcirostris_Groove-billed Ani",
    "Crypturellus cinereus_Cinereous Tinamou",
    "Crypturellus strigulosus_Brazilian Tinamou",
    "Crypturellus undulatus_Undulated Tinamou",
    "Cuculus canorus_Common Cuckoo",
    "Cuculus lepidus_Sunda Cuckoo",
    "Cuculus solitarius_Red-chested Cuckoo",
    "Curruca communis_Greater Whitethroat",
    "Curruca curruca_Lesser Whitethroat",
    "Cyanerpes cyaneus_Red-legged Honeycreeper",
    "Cyanistes caeruleus_Eurasian Blue Tit",
    "Cyanocitta cristata_Blue Jay",
    "Cyanocitta stelleri_Steller's Jay",
    "Cyanocompsa parellina_Blue Bunting",
    "Cyanocorax yncas_Green Jay",
    "Cyanocorax yucatanicus_Yucatan Jay",
    "Cyanoderma erythropterum_Chestnut-winged Babbler",
    "Cyanoderma rufifrons_Rufous-fronted Babbler",
    "Cyclarhis gujanensis_Rufous-browed Peppershrike",
    "Cygnus atratus_Black Swan",
    "Cygnus olor_Mute Swan",
    "Cyornis olivaceus_Fulvous-chested Jungle-Flycatcher",
    "Cyornis turcosus_Malaysian Blue Flycatcher",
    "Cyornis umbratilis_Gray-chested Jungle-Flycatcher",
    "Cypsiurus parvus_African Palm-Swift",
    "Dacelo novaeguineae_Laughing Kookaburra",
    "Dacnis cayana_Blue Dacnis",
    "Daphoenositta chrysoptera_Varied Sittella",
    "Delichon urbicum_Common House-Martin",
    "Dendrocitta cinerascens_Bornean Treepie",
    "Dendrocopos major_Great Spotted Woodpecker",
    "Dendrocoptes medius_Middle Spotted Woodpecker",
    "Dendrocygna autumnalis_Black-bellied Whistling-Duck",
    "Dendrocygna viduata_White-faced Whistling-Duck",
    "Dendroplex picus_Straight-billed Woodcreeper",
    "Dicaeum chrysorrheum_Yellow-vented Flowerpecker",
    "Dicaeum hirundinaceum_Mistletoebird",
    "Dicaeum trigonostigma_Orange-bellied Flowerpecker",
    "Dicrurus atripennis_Shining Drongo",
    "Dicrurus paradiseus_Greater Racket-tailed Drongo",
    "Diopsittaca nobilis_Red-shouldered Macaw",
    "Dives dives_Melodious Blackbird",
    "Dolichonyx oryzivorus_Bobolink",
    "Drymophila devillei_Striated Antbird",
    "Dryobates minor_Lesser Spotted Woodpecker",
    "Dryobates pubescens_Downy Woodpecker",
    "Dryobates villosus_Hairy Woodpecker",
    "Dryocopus lineatus_Lineated Woodpecker",
    "Dryocopus martius_Black Woodpecker",
    "Dryocopus pileatus_Pileated Woodpecker",
    "Dryotriorchis spectabilis_Congo Serpent-Eagle",
    "Ducula aenea_Green Imperial-Pigeon",
    "Dumetella carolinensis_Gray Catbird",
    "Egretta caerulea_Little Blue Heron",
    "Egretta garzetta_Little Egret",
    "Egretta novaehollandiae_White-faced Heron",
    "Egretta thula_Snowy Egret",
    "Egretta tricolor_Tricolored Heron",
    "Elaenia flavogaster_Yellow-bellied Elaenia",
    "Elminia longicauda_African Blue Flycatcher",
    "Elseyornis melanops_Black-fronted Dotterel",
    "Emberiza cabanisi_Cabanis's Bunting",
    "Emberiza calandra_Corn Bunting",
    "Emberiza citrinella_Yellowhammer",
    "Emberiza schoeniclus_Reed Bunting",
    "Empidonax alnorum_Alder Flycatcher",
    "Empidonax flaviventris_Yellow-bellied Flycatcher",
    "Empidonax minimus_Least Flycatcher",
    "Empidonax traillii_Willow Flycatcher",
    "Empidonax virescens_Acadian Flycatcher",
    "Empidonax wrightii_Gray Flycatcher",
    "Entomyzon cyanotis_Blue-faced Honeyeater",
    "Eolophus roseicapilla_Galah",
    "Eopsaltria australis_Eastern Yellow Robin",
    "Epinecrophylla leucophthalma_White-eyed Stipplethroat",
    "Eremophila alpestris_Horned Lark",
    "Erithacus rubecula_European Robin",
    "Erpornis zantholeuca_White-bellied Erpornis",
    "Erythropitta granatina_Garnet Pitta",
    "Estrilda astrild_Common Waxbill",
    "Estrilda nonnula_Black-crowned Waxbill",
    "Eudocimus albus_White Ibis",
    "Eudynamys orientalis_Pacific Koel",
    "Eumomota superciliosa_Turquoise-browed Motmot",
    "Eumyias indigo_Indigo Flycatcher",
    "Eupetes macrocerus_Malaysian Rail-babbler",
    "Euphagus cyanocephalus_Brewer's Blackbird",
    "Euphonia affinis_Scrub Euphonia",
    "Euphonia chlorotica_Purple-throated Euphonia",
    "Euphonia chrysopasta_Golden-bellied Euphonia",
    "Euphonia hirundinacea_Yellow-throated Euphonia",
    "Euphonia rufiventris_Rufous-bellied Euphonia",
    "Euphonia violacea_Violaceous Euphonia",
    "Eupsittula aurea_Peach-fronted Parakeet",
    "Eupsittula nana_Olive-throated Parakeet",
    "Eurillas ansorgei_Ansorge's Greenbul",
    "Eurillas curvirostris_Plain Greenbul",
    "Eurillas latirostris_Yellow-whiskered Greenbul",
    "Eurillas virens_Little Greenbul",
    "Eurylaimus ochromalus_Black-and-yellow Broadbill",
    "Eurystomus glaucurus_Broad-billed Roller",
    "Eurystomus orientalis_Dollarbird",
    "Falco berigora_Brown Falcon",
    "Falco mexicanus_Prairie Falcon",
    "Falco sparverius_American Kestrel",
    "Falco subbuteo_Eurasian Hobby",
    "Falco tinnunculus_Eurasian Kestrel",
    "Falcunculus frontatus_Crested Shrike-tit",
    "Ficedula dumetoria_Rufous-chested Flycatcher",
    "Ficedula hypoleuca_European Pied Flycatcher",
    "Forpus xanthopterygius_Cobalt-rumped Parrotlet",
    "Fraseria griseigularis_Gray-throated Tit-Flycatcher",
    "Fraseria ocreata_African Forest-Flycatcher",
    "Fregata ariel_Lesser Frigatebird",
    "Fregata magnificens_Magnificent Frigatebird",
    "Fringilla coelebs_Common Chaffinch",
    "Fringilla montifringilla_Brambling",
    "Fulica americana_American Coot",
    "Fulica atra_Eurasian Coot",
    "Furnarius rufus_Rufous Hornero",
    "Galbula ruficauda_Rufous-tailed Jacamar",
    "Gallinago gallinago_Common Snipe",
    "Gallinula chloropus_Eurasian Moorhen",
    "Gallinula tenebrosa_Dusky Moorhen",
    "Garrulax palliatus_Sunda Laughingthrush",
    "Garrulus glandarius_Eurasian Jay",
    "Gavia immer_Common Loon",
    "Gelochelidon nilotica_Gull-billed Tern",
    "Geopelia humeralis_Bar-shouldered Dove",
    "Geopelia placida_Peaceful Dove",
    "Geopelia striata_Zebra Dove",
    "Geothlypis formosa_Kentucky Warbler",
    "Geothlypis poliocephala_Gray-crowned Yellowthroat",
    "Geothlypis tolmiei_MacGillivray's Warbler",
    "Geothlypis trichas_Common Yellowthroat",
    "Gerygone mouki_Brown Gerygone",
    "Gerygone olivacea_White-throated Gerygone",
    "Glaucidium brasilianum_Ferruginous Pygmy-Owl",
    "Glaucidium hardyi_Amazonian Pygmy-Owl",
    "Glaucidium tephronotum_Red-chested Owlet",
    "Glossopsitta concinna_Musk Lorikeet",
    "Gracula religiosa_Common Hill Myna",
    "Grallina cyanoleuca_Magpie-lark",
    "Granatellus pelzelni_Rose-breasted Chat",
    "Grus grus_Common Crane",
    "Guira guira_Guira Cuckoo",
    "Gymnobucco bonapartei_Gray-throated Barbet",
    "Gymnobucco calvus_Naked-faced Barbet",
    "Gymnorhina tibicen_Australian Magpie",
    "Gymnoris superciliaris_Yellow-throated Bush Sparrow",
    "Habia fuscicauda_Red-throated Ant-Tanager",
    "Haemorhous cassinii_Cassin's Finch",
    "Haemorhous mexicanus_House Finch",
    "Haemorhous purpureus_Purple Finch",
    "Halcyon albiventris_Brown-hooded Kingfisher",
    "Halcyon badia_Chocolate-backed Kingfisher",
    "Halcyon malimbica_Blue-breasted Kingfisher",
    "Halcyon senegalensis_Woodland Kingfisher",
    "Haliaeetus albicilla_White-tailed Eagle",
    "Haliaeetus leucocephalus_Bald Eagle",
    "Haliaeetus leucogaster_White-bellied Sea-Eagle",
    "Haliaeetus vocifer_African Fish-Eagle",
    "Haliastur sphenurus_Whistling Kite",
    "Harpactes diardii_Diard's Trogon",
    "Harpactes duvaucelii_Scarlet-rumped Trogon",
    "Harpactes oreskios_Orange-breasted Trogon",
    "Harpactes orrhophaeus_Cinnamon-rumped Trogon",
    "Hedydipna collaris_Collared Sunbird",
    "Hedydipna platura_Pygmy Sunbird",
    "Hemicircus concretus_Gray-and-buff Woodpecker",
    "Hemiprocne longipennis_Gray-rumped Treeswift",
    "Hemipus hirundinaceus_Black-winged Flycatcher-shrike",
    "Hemitriccus minor_Snethlage's Tody-Tyrant",
    "Hemixos cinereus_Cinereous Bulbul",
    "Herpetotheres cachinnans_Laughing Falcon",
    "Heterocercus linteatus_Flame-crowned Manakin",
    "Hierococcyx bocki_Dark Hawk-Cuckoo",
    "Hierococcyx vagans_Moustached Hawk-Cuckoo",
    "Himantopus leucocephalus_Pied Stilt",
    "Himantopus mexicanus_Black-necked Stilt",
    "Hippolais icterina_Icterine Warbler",
    "Hirundapus caudacutus_White-throated Needletail",
    "Hirundo neoxena_Welcome Swallow",
    "Hirundo rustica_Barn Swallow",
    "Hirundo tahitica_Pacific Swallow",
    "Horornis vulcanius_Sunda Bush Warbler",
    "Hydroprogne caspia_Caspian Tern",
    "Hydrornis caeruleus_Giant Pitta",
    "Hylia prasina_Green Hylia",
    "Hylocichla mustelina_Wood Thrush",
    "Hylophilus semicinereus_Gray-chested Greenlet",
    "Hylophylax naevius_Spot-backed Antbird",
    "Hypergerus atriceps_Oriole Warbler",
    "Hypocnemoides maculicauda_Band-tailed Antbird",
    "Ibycter americanus_Red-throated Caracara",
    "Icteria virens_Yellow-breasted Chat",
    "Icterus auratus_Orange Oriole",
    "Icterus bullockii_Bullock's Oriole",
    "Icterus cucullatus_Hooded Oriole",
    "Icterus galbula_Baltimore Oriole",
    "Icterus gularis_Altamira Oriole",
    "Icterus prosthemelas_Black-cowled Oriole",
    "Icterus spurius_Orchard Oriole",
    "Illadopsis cleaveri_Blackcap Illadopsis",
    "Illadopsis fulvescens_Brown Illadopsis",
    "Illadopsis rufipennis_Pale-breasted Illadopsis",
    "Irena puella_Asian Fairy-bluebird",
    "Ixonotus guttatus_Spotted Greenbul",
    "Ixos malaccensis_Streaked Bulbul",
    "Jacana jacana_Wattled Jacana",
    "Jacana spinosa_Northern Jacana",
    "Junco hyemalis_Dark-eyed Junco",
    "Kenopia striata_Striped Wren-Babbler",
    "Lacedo pulchella_Banded Kingfisher",
    "Lalage fimbriata_Lesser Cuckooshrike",
    "Lalage tricolor_White-winged Triller",
    "Lamprotornis splendidus_Splendid Starling",
    "Laniarius bicolor_Gabon Boubou",
    "Lanius collurio_Red-backed Shrike",
    "Lanius ludovicianus_Loggerhead Shrike",
    "Lanius schach_Long-tailed Shrike",
    "Larus argentatus_Herring Gull",
    "Larus cachinnans_Caspian Gull",
    "Larus californicus_California Gull",
    "Larus canus_Common Gull",
    "Larus delawarensis_Ring-billed Gull",
    "Larus michahellis_Yellow-legged Gull",
    "Leiothlypis celata_Orange-crowned Warbler",
    "Leiothlypis peregrina_Tennessee Warbler",
    "Leiothlypis ruficapilla_Nashville Warbler",
    "Lepidothrix nattereri_Snow-capped Manakin",
    "Leptotila verreauxi_White-tipped Dove",
    "Leucophaeus atricilla_Laughing Gull",
    "Leucosarcia melanoleuca_Wonga Pigeon",
    "Lichenostomus melanops_Yellow-tufted Honeyeater",
    "Lichmera indistincta_Brown Honeyeater",
    "Limnodromus scolopaceus_Long-billed Dowitcher",
    "Linaria cannabina_Eurasian Linnet",
    "Lipaugus vociferans_Screaming Piha",
    "Locustella luscinioides_Savi's Warbler",
    "Locustella naevia_Common Grasshopper-Warbler",
    "Lonchura atricapilla_Chestnut Munia",
    "Lophaetus occipitalis_Long-crested Eagle",
    "Lophoceros camurus_Red-billed Dwarf Hornbill",
    "Lophodytes cucullatus_Hooded Merganser",
    "Lophophanes cristatus_Crested Tit",
    "Loxia curvirostra_Red Crossbill",
    "Lullula arborea_Wood Lark",
    "Luscinia megarhynchos_Common Nightingale",
    "Machaeropterus pyrocephalus_Fiery-capped Manakin",
    "Macronus ptilosus_Fluffy-backed Tit-Babbler",
    "Macropygia phasianella_Brown Cuckoo-Dove",
    "Macropygia ruficeps_Little Cuckoo-Dove",
    "Macrosphenus concolor_Gray Longbill",
    "Macrosphenus flavicans_Yellow Longbill",
    "Malacopteron cinereum_Scaly-crowned Babbler",
    "Malacopteron magnum_Rufous-crowned Babbler",
    "Malacorhynchus membranaceus_Pink-eared Duck",
    "Malimbus nitens_Blue-billed Malimbe",
    "Malurus cyaneus_Superb Fairywren",
    "Malurus lamberti_Variegated Fairywren",
    "Manorina melanocephala_Noisy Miner",
    "Mareca americana_American Wigeon",
    "Mareca penelope_Eurasian Wigeon",
    "Mareca strepera_Gadwall",
    "Megaceryle alcyon_Belted Kingfisher",
    "Megaceryle maxima_Giant Kingfisher",
    "Megaceryle torquata_Ringed Kingfisher",
    "Megarynchus pitangua_Boat-billed Flycatcher",
    "Meiglyptes tristis_Buff-rumped Woodpecker",
    "Melanerpes aurifrons_Golden-fronted Woodpecker",
    "Melanerpes carolinus_Red-bellied Woodpecker",
    "Melanerpes cruentatus_Yellow-tufted Woodpecker",
    "Melanerpes formicivorus_Acorn Woodpecker",
    "Melanerpes pygmaeus_Yucatan Woodpecker",
    "Melaniparus funereus_Dusky Tit",
    "Melaniparus leucomelas_White-winged Black-Tit",
    "Melaniparus rufiventris_Rufous-bellied Tit",
    "Meleagris gallopavo_Wild Turkey",
    "Meliphaga lewinii_Lewin's Honeyeater",
    "Melithreptus brevirostris_Brown-headed Honeyeater",
    "Melithreptus lunatus_White-naped Honeyeater",
    "Melospiza georgiana_Swamp Sparrow",
    "Melospiza lincolnii_Lincoln's Sparrow",
    "Melospiza melodia_Song Sparrow",
    "Menura novaehollandiae_Superb Lyrebird",
    "Mergus merganser_Common Merganser",
    "Mergus serrator_Red-breasted Merganser",
    "Merops ornatus_Rainbow Bee-eater",
    "Merops persicus_Blue-cheeked Bee-eater",
    "Merops viridis_Blue-throated Bee-eater",
    "Mesembrinibis cayennensis_Green Ibis",
    "Microeca fascinans_Jacky-winter",
    "Milvus migrans_Black Kite",
    "Milvus milvus_Red Kite",
    "Mimus gilvus_Tropical Mockingbird",
    "Mimus polyglottos_Northern Mockingbird",
    "Mixornis bornensis_Bold-striped Tit-Babbler",
    "Mniotilta varia_Black-and-white Warbler",
    "Molothrus aeneus_Bronzed Cowbird",
    "Molothrus ater_Brown-headed Cowbird",
    "Molothrus bonariensis_Shiny Cowbird",
    "Momotus lessonii_Lesson's Motmot",
    "Momotus momota_Amazonian Motmot",
    "Monarcha melanopsis_Black-faced Monarch",
    "Monasa nigrifrons_Black-fronted Nunbird",
    "Motacilla alba_White Wagtail",
    "Motacilla cinerea_Gray Wagtail",
    "Motacilla flava_Western Yellow Wagtail",
    "Motacilla tschutschensis_Eastern Yellow Wagtail",
    "Muscicapa dauurica_Asian Brown Flycatcher",
    "Muscicapa griseisticta_Gray-streaked Flycatcher",
    "Muscicapa striata_Spotted Flycatcher",
    "Myadestes townsendi_Townsend's Solitaire",
    "Mycteria americana_Wood Stork",
    "Myiagra inquieta_Restless Flycatcher",
    "Myiagra rubecula_Leaden Flycatcher",
    "Myiarchus cinerascens_Ash-throated Flycatcher",
    "Myiarchus crinitus_Great Crested Flycatcher",
    "Myiarchus tuberculifer_Dusky-capped Flycatcher",
    "Myiarchus tyrannulus_Brown-crested Flycatcher",
    "Myiodynastes luteiventris_Sulphur-bellied Flycatcher",
    "Myiodynastes maculatus_Streaked Flycatcher",
    "Myiopagis gaimardii_Forest Elaenia",
    "Myiornis ecaudatus_Short-tailed Pygmy-Tyrant",
    "Myiozetetes cayanensis_Rusty-margined Flycatcher",
    "Myiozetetes similis_Social Flycatcher",
    "Myrmecocichla nigra_Sooty Chat",
    "Myrmelastes rufifacies_Rufous-faced Antbird",
    "Myrmoborus myotherinus_Black-faced Antbird",
    "Myrmoderus ferrugineus_Ferruginous-backed Antbird",
    "Myrmothera berlepschi_Amazonian Antpitta",
    "Myrmothera subcanescens_Tapajos Antpitta",
    "Myrmotherula brachyura_Pygmy Antwren",
    "Myrmotherula sclateri_Sclater's Antwren",
    "Myzomela sanguinolenta_Scarlet Myzomela",
    "Nannopterum auritum_Double-crested Cormorant",
    "Nannopterum brasilianum_Neotropic Cormorant",
    "Napothera epilepidota_Eyebrowed Wren-Babbler",
    "Neochmia temporalis_Red-browed Firetail",
    "Neocossyphus fraseri_Rufous Flycatcher-Thrush",
    "Neocossyphus poensis_White-tailed Ant-Thrush",
    "Nesoptilotis leucotis_White-eared Honeyeater",
    "Netta rufina_Red-crested Pochard",
    "Nicator chloris_Western Nicator",
    "Nicator vireo_Yellow-throated Nicator",
    "Ninox japonica_Northern Boobook",
    "Nisaetus nanus_Wallace's Hawk-Eagle",
    "Numenius americanus_Long-billed Curlew",
    "Numenius arquata_Eurasian Curlew",
    "Numenius madagascariensis_Far Eastern Curlew",
    "Nycticorax nycticorax_Black-crowned Night-Heron",
    "Nystalus striolatus_Eastern Striolated-Puffbird",
    "Ocyphaps lophotes_Crested Pigeon",
    "Odontorchilus cinereus_Tooth-billed Wren",
    "Oncostoma cinereigulare_Northern Bentbill",
    "Oriolus brachyrynchus_Western Black-headed Oriole",
    "Oriolus cruentus_Black-and-crimson Oriole",
    "Oriolus nigripennis_Black-winged Oriole",
    "Oriolus oriolus_Eurasian Golden Oriole",
    "Oriolus sagittatus_Olive-backed Oriole",
    "Ornithion inerme_White-lored Tyrannulet",
    "Ortalis vetula_Plain Chachalaca",
    "Orthotomus ruficeps_Ashy Tailorbird",
    "Orthotomus sericeus_Rufous-tailed Tailorbird",
    "Otus rufescens_Reddish Scops-Owl",
    "Otus spilocephalus_Mountain Scops-Owl",
    "Oxyura jamaicensis_Ruddy Duck",
    "Pachycephala hypoxantha_Bornean Whistler",
    "Pachycephala pectoralis_Golden Whistler",
    "Pachycephala rufiventris_Rufous Whistler",
    "Pachyramphus aglaiae_Rose-throated Becard",
    "Pachysylvia decurtata_Lesser Greenlet",
    "Pachysylvia hypoxantha_Dusky-capped Greenlet",
    "Pachysylvia muscicapina_Buff-cheeked Greenlet",
    "Pandion haliaetus_Osprey",
    "Pardalotus punctatus_Spotted Pardalote",
    "Pardalotus striatus_Striated Pardalote",
    "Parkesia noveboracensis_Northern Waterthrush",
    "Parus major_Great Tit",
    "Parvipsitta pusilla_Little Lorikeet",
    "Passer domesticus_House Sparrow",
    "Passer griseus_Northern Gray-headed Sparrow",
    "Passer montanus_Eurasian Tree Sparrow",
    "Passerculus sandwichensis_Savannah Sparrow",
    "Passerina amoena_Lazuli Bunting",
    "Passerina cyanea_Indigo Bunting",
    "Patagioenas cayennensis_Pale-vented Pigeon",
    "Patagioenas flavirostris_Red-billed Pigeon",
    "Patagioenas picazuro_Picazuro Pigeon",
    "Pelecanus conspicillatus_Australian Pelican",
    "Pelecanus erythrorhynchos_American White Pelican",
    "Pelecanus occidentalis_Brown Pelican",
    "Pellorneum malaccense_Short-tailed Babbler",
    "Pellorneum pyrrogenys_Temminck's Babbler",
    "Pellorneum rostratum_White-chested Babbler",
    "Penelope jacquacu_Spix's Guan",
    "Pericrocotus solaris_Gray-chinned Minivet",
    "Periparus ater_Coal Tit",
    "Petrochelidon ariel_Fairy Martin",
    "Petrochelidon nigricans_Tree Martin",
    "Petrochelidon pyrrhonota_Cliff Swallow",
    "Petroica rosea_Rose Robin",
    "Phaenicophaeus sumatranus_Chestnut-bellied Malkoha",
    "Phainopepla nitens_Phainopepla",
    "Phalacrocorax carbo_Great Cormorant",
    "Phalaropus tricolor_Wilson's Phalarope",
    "Phaps chalcoptera_Common Bronzewing",
    "Phasianus colchicus_Ring-necked Pheasant",
    "Pheucticus ludovicianus_Rose-breasted Grosbeak",
    "Pheucticus melanocephalus_Black-headed Grosbeak",
    "Pheugopedius genibarbis_Moustached Wren",
    "Pheugopedius maculipectus_Spot-breasted Wren",
    "Philemon corniculatus_Noisy Friarbird",
    "Philentoma velata_Maroon-breasted Philentoma",
    "Philydor pyrrhodes_Cinnamon-rumped Foliage-gleaner",
    "Phodilus badius_Oriental Bay-Owl",
    "Phoenicurus ochruros_Black Redstart",
    "Phoenicurus phoenicurus_Common Redstart",
    "Phylidonyris novaehollandiae_New Holland Honeyeater",
    "Phyllergates cucullatus_Mountain Tailorbird",
    "Phylloscopus budongoensis_Uganda Woodland-Warbler",
    "Phylloscopus collybita_Common Chiffchaff",
    "Phylloscopus montis_Yellow-breasted Warbler",
    "Phylloscopus sibilatrix_Wood Warbler",
    "Phylloscopus trochilus_Willow Warbler",
    "Piaya cayana_Squirrel Cuckoo",
    "Piaya melanogaster_Black-bellied Cuckoo",
    "Pica pica_Eurasian Magpie",
    "Picumnus aurifrons_Bar-breasted Piculet",
    "Picus viridis_Eurasian Green Woodpecker",
    "Pionites leucogaster_White-bellied Parrot",
    "Pionus menstruus_Blue-headed Parrot",
    "Pipilo chlorurus_Green-tailed Towhee",
    "Pipilo erythrophthalmus_Eastern Towhee",
    "Pipilo maculatus_Spotted Towhee",
    "Pipra fasciicauda_Band-tailed Manakin",
    "Piranga ludoviciana_Western Tanager",
    "Piranga olivacea_Scarlet Tanager",
    "Piranga rubra_Summer Tanager",
    "Pitangus sulphuratus_Great Kiskadee",
    "Platycercus elegans_Crimson Rosella",
    "Platycercus eximius_Eastern Rosella",
    "Platylophus galericulatus_Crested Shrikejay",
    "Platyrinchus platyrhynchos_White-crested Spadebill",
    "Platysmurus leucopterus_Black Magpie",
    "Platysteira castanea_Chestnut Wattle-eye",
    "Plectorhyncha lanceolata_Striped Honeyeater",
    "Plegadis chihi_White-faced Ibis",
    "Ploceus cucullatus_Village Weaver",
    "Podiceps auritus_Horned Grebe",
    "Podiceps cristatus_Great Crested Grebe",
    "Podiceps nigricollis_Eared Grebe",
    "Podilymbus podiceps_Pied-billed Grebe",
    "Poecile atricapillus_Black-capped Chickadee",
    "Poecile gambeli_Mountain Chickadee",
    "Poecile montanus_Willow Tit",
    "Poecile palustris_Marsh Tit",
    "Poecilotriccus latirostris_Rusty-fronted Tody-Flycatcher",
    "Pogoniulus atroflavus_Red-rumped Tinkerbird",
    "Pogoniulus bilineatus_Yellow-rumped Tinkerbird",
    "Pogoniulus scolopaceus_Speckled Tinkerbird",
    "Pogoniulus subsulphureus_Yellow-throated Tinkerbird",
    "Polioptila caerulea_Blue-gray Gnatcatcher",
    "Polioptila dumicola_Masked Gnatcatcher",
    "Polyboroides typus_African Harrier-Hawk",
    "Pooecetes gramineus_Vesper Sparrow",
    "Porphyrio melanotus_Australasian Swamphen",
    "Prinia flaviventris_Yellow-bellied Prinia",
    "Prinia subflava_Tawny-flanked Prinia",
    "Prionochilus xanthopygius_Yellow-rumped Flowerpecker",
    "Progne chalybea_Gray-breasted Martin",
    "Progne subis_Purple Martin",
    "Prunella modularis_Dunnock",
    "Psaltriparus minimus_Bushtit",
    "Psarisomus dalhousiae_Long-tailed Broadbill",
    "Psephotus haematonotus_Red-rumped Parrot",
    "Psilopogon duvaucelii_Blue-eared Barbet",
    "Psilopogon eximius_Bornean Barbet",
    "Psilopogon monticola_Mountain Barbet",
    "Psilopogon mystacophanos_Red-throated Barbet",
    "Psilopogon pulcherrimus_Golden-naped Barbet",
    "Psilorhinus morio_Brown Jay",
    "Psittacara leucophthalmus_White-eyed Parakeet",
    "Psittacus erithacus_Gray Parrot",
    "Psophia viridis_Dark-winged Trumpeter",
    "Psophodes olivaceus_Eastern Whipbird",
    "Pterorhinus treacheri_Chestnut-hooded Laughingthrush",
    "Pteruthius aeralatus_Blyth's Shrike-Babbler",
    "Ptilonorhynchus violaceus_Satin Bowerbird",
    "Ptilopsis leucotis_Northern White-faced Owl",
    "Ptilotula fusca_Fuscous Honeyeater",
    "Ptilotula penicillata_White-plumed Honeyeater",
    "Pycnonotus barbatus_Common Bulbul",
    "Pycnonotus brunneus_Red-eyed Bulbul",
    "Pycnonotus flavescens_Flavescent Bulbul",
    "Pycnonotus goiavier_Yellow-vented Bulbul",
    "Pycnonotus plumosus_Olive-winged Bulbul",
    "Pyrocephalus rubinus_Vermilion Flycatcher",
    "Pyrrholaemus sagittatus_Speckled Warbler",
    "Pyrrhula pyrrhula_Eurasian Bullfinch",
    "Pyrrhura amazonum_Santarem Parakeet",
    "Pyrrhura perlata_Crimson-bellied Parakeet",
    "Quiscalus mexicanus_Great-tailed Grackle",
    "Quiscalus quiscula_Common Grackle",
    "Rallus aquaticus_Water Rail",
    "Ramphastos sulfuratus_Keel-billed Toucan",
    "Ramphastos tucanus_White-throated Toucan",
    "Ramphastos vitellinus_Channel-billed Toucan",
    "Ramphocelus carbo_Silver-beaked Tanager",
    "Recurvirostra americana_American Avocet",
    "Regulus ignicapilla_Common Firecrest",
    "Regulus regulus_Goldcrest",
    "Regulus satrapa_Golden-crowned Kinglet",
    "Rhabdotorrhinus corrugatus_Wrinkled Hornbill",
    "Rhipidura albicollis_White-throated Fantail",
    "Rhipidura albiscapa_Gray Fantail",
    "Rhipidura leucophrys_Willie-wagtail",
    "Rhipidura rufifrons_Rufous Fantail",
    "Riparia riparia_Bank Swallow",
    "Rollulus rouloul_Crested Partridge",
    "Rupornis magnirostris_Roadside Hawk",
    "Rynchops niger_Black Skimmer",
    "Sakesphorus luctuosus_Glossy Antshrike",
    "Salpinctes obsoletus_Rock Wren",
    "Saltator atriceps_Black-headed Saltator",
    "Saltator grandis_Cinnamon-bellied Saltator",
    "Sarothrura elegans_Buff-spotted Flufftail",
    "Sarothrura pulchra_White-spotted Flufftail",
    "Saxicola rubetra_Whinchat",
    "Saxicola rubicola_European Stonechat",
    "Sayornis nigricans_Black Phoebe",
    "Sayornis phoebe_Eastern Phoebe",
    "Sayornis saya_Say's Phoebe",
    "Sciaphylax hemimelaena_Chestnut-tailed Antbird",
    "Sclerurus rufigularis_Short-billed Leaftosser",
    "Scopus umbretta_Hamerkop",
    "Scythrops novaehollandiae_Channel-billed Cuckoo",
    "Seiurus aurocapilla_Ovenbird",
    "Selasphorus rufus_Rufous Hummingbird",
    "Sericornis frontalis_White-browed Scrubwren",
    "Serinus serinus_European Serin",
    "Setophaga americana_Northern Parula",
    "Setophaga caerulescens_Black-throated Blue Warbler",
    "Setophaga castanea_Bay-breasted Warbler",
    "Setophaga citrina_Hooded Warbler",
    "Setophaga coronata_Yellow-rumped Warbler",
    "Setophaga dominica_Yellow-throated Warbler",
    "Setophaga fusca_Blackburnian Warbler",
    "Setophaga magnolia_Magnolia Warbler",
    "Setophaga nigrescens_Black-throated Gray Warbler",
    "Setophaga palmarum_Palm Warbler",
    "Setophaga pensylvanica_Chestnut-sided Warbler",
    "Setophaga petechia_Yellow Warbler",
    "Setophaga pinus_Pine Warbler",
    "Setophaga ruticilla_American Redstart",
    "Setophaga striata_Blackpoll Warbler",
    "Setophaga tigrina_Cape May Warbler",
    "Setophaga virens_Black-throated Green Warbler",
    "Sialia currucoides_Mountain Bluebird",
    "Sialia mexicana_Western Bluebird",
    "Sialia sialis_Eastern Bluebird",
    "Sicalis flaveola_Saffron Finch",
    "Sitta canadensis_Red-breasted Nuthatch",
    "Sitta carolinensis_White-breasted Nuthatch",
    "Sitta europaea_Eurasian Nuthatch",
    "Sittasomus griseicapillus_Olivaceous Woodcreeper",
    "Smicrornis brevirostris_Weebill",
    "Smithornis capensis_African Broadbill",
    "Smithornis rufolateralis_Rufous-sided Broadbill",
    "Spatula clypeata_Northern Shoveler",
    "Spatula cyanoptera_Cinnamon Teal",
    "Spatula discors_Blue-winged Teal",
    "Spatula querquedula_Garganey",
    "Spermestes cucullata_Bronze Mannikin",
    "Spermophaga haematina_Western Bluebill",
    "Sphecotheres vieilloti_Australasian Figbird",
    "Sphyrapicus ruber_Red-breasted Sapsucker",
    "Sphyrapicus varius_Yellow-bellied Sapsucker",
    "Spinus pinus_Pine Siskin",
    "Spinus psaltria_Lesser Goldfinch",
    "Spinus spinus_Eurasian Siskin",
    "Spinus tristis_American Goldfinch",
    "Spizella breweri_Brewer's Sparrow",
    "Spizella passerina_Chipping Sparrow",
    "Spizella pusilla_Field Sparrow",
    "Spizelloides arborea_American Tree Sparrow",
    "Sporophila morelleti_Morelet's Seedeater",
    "Stachyris nigriceps_Gray-throated Babbler",
    "Stachyris nigricollis_Black-throated Babbler",
    "Stachyris poliocephala_Gray-headed Babbler",
    "Stelgidopteryx ruficollis_Southern Rough-winged Swallow",
    "Stelgidopteryx serripennis_Northern Rough-winged Swallow",
    "Sterna hirundo_Common Tern",
    "Stiphrornis erythrothorax_Forest Robin",
    "Stizoptera bichenovii_Double-barred Finch",
    "Strepera graculina_Pied Currawong",
    "Streptopelia capicola_Ring-necked Dove",
    "Streptopelia chinensis_Spotted Dove",
    "Streptopelia decaocto_Eurasian Collared-Dove",
    "Streptopelia semitorquata_Red-eyed Dove",
    "Streptopelia senegalensis_Laughing Dove",
    "Streptopelia turtur_European Turtle-Dove",
    "Sturnella magna_Eastern Meadowlark",
    "Sturnella neglecta_Western Meadowlark",
    "Sturnus vulgaris_European Starling",
    "Sylvia atricapilla_Eurasian Blackcap",
    "Sylvia borin_Garden Warbler",
    "Sylvietta ruficapilla_Red-capped Crombec",
    "Sylvietta virens_Green Crombec",
    "Synoicus ypsilophorus_Brown Quail",
    "Tachornis squamata_Fork-tailed Palm-Swift",
    "Tachybaptus novaehollandiae_Australasian Grebe",
    "Tachybaptus ruficollis_Little Grebe",
    "Tachycineta albilinea_Mangrove Swallow",
    "Tachycineta albiventer_White-winged Swallow",
    "Tachycineta bicolor_Tree Swallow",
    "Tachycineta thalassina_Violet-green Swallow",
    "Tauraco macrorhynchus_Yellow-billed Turaco",
    "Tauraco persa_Guinea Turaco",
    "Tchagra senegalus_Black-crowned Tchagra",
    "Telophorus viridis_Four-colored Bushshrike",
    "Terpsiphone affinis_Blyth's Paradise-Flycatcher",
    "Terpsiphone rufiventer_Black-headed Paradise-Flycatcher",
    "Terpsiphone viridis_African Paradise-Flycatcher",
    "Thalasseus bergii_Great Crested Tern",
    "Thalasseus maximus_Royal Tern",
    "Thalasseus sandvicensis_Sandwich Tern",
    "Thamnophilus doliatus_Barred Antshrike",
    "Thamnophilus schistaceus_Plain-winged Antshrike",
    "Theristicus caudatus_Buff-necked Ibis",
    "Thescelocichla leucopleura_Swamp Greenbul",
    "Thraupis abbas_Yellow-winged Tanager",
    "Thraupis episcopus_Blue-gray Tanager",
    "Thraupis palmarum_Palm Tanager",
    "Threskiornis molucca_Australian Ibis",
    "Thryomanes bewickii_Bewick's Wren",
    "Thryothorus ludovicianus_Carolina Wren",
    "Tiaris olivaceus_Yellow-faced Grassquit",
    "Tigrisoma mexicanum_Bare-throated Tiger-Heron",
    "Tityra semifasciata_Masked Tityra",
    "Todiramphus chloris_Collared Kingfisher",
    "Todiramphus sanctus_Sacred Kingfisher",
    "Tolmomyias sulphurescens_Yellow-olive Flycatcher",
    "Toxostoma rufum_Brown Thrasher",
    "Trachyphonus purpuratus_Yellow-billed Barbet",
    "Treron calvus_African Green-Pigeon",
    "Treron fulvicollis_Cinnamon-headed Green-Pigeon",
    "Treron vernans_Pink-necked Green-Pigeon",
    "Trichoglossus chlorolepidotus_Scaly-breasted Lorikeet",
    "Trichoglossus moluccanus_Rainbow Lorikeet",
    "Tringa erythropus_Spotted Redshank",
    "Tringa flavipes_Lesser Yellowlegs",
    "Tringa glareola_Wood Sandpiper",
    "Tringa melanoleuca_Greater Yellowlegs",
    "Tringa nebularia_Common Greenshank",
    "Tringa ochropus_Green Sandpiper",
    "Tringa solitaria_Solitary Sandpiper",
    "Trochocercus nitens_Blue-headed Crested-Flycatcher",
    "Troglodytes aedon_House Wren",
    "Troglodytes hiemalis_Winter Wren",
    "Troglodytes troglodytes_Eurasian Wren",
    "Trogon caligatus_Gartered Trogon",
    "Trogon curucui_Blue-crowned Trogon",
    "Trogon melanocephalus_Black-headed Trogon",
    "Trogon melanurus_Black-tailed Trogon",
    "Turdoides reinwardtii_Blackcap Babbler",
    "Turdus amaurochalinus_Creamy-bellied Thrush",
    "Turdus grayi_Clay-colored Thrush",
    "Turdus iliacus_Redwing",
    "Turdus merula_Eurasian Blackbird",
    "Turdus migratorius_American Robin",
    "Turdus pelios_African Thrush",
    "Turdus philomelos_Song Thrush",
    "Turdus pilaris_Fieldfare",
    "Turdus viscivorus_Mistle Thrush",
    "Turtur brehmeri_Blue-headed Wood-Dove",
    "Turtur chalcospilos_Emerald-spotted Wood-Dove",
    "Tyranneutes stolzmanni_Dwarf Tyrant-Manakin",
    "Tyrannus couchii_Couch's Kingbird",
    "Tyrannus melancholicus_Tropical Kingbird",
    "Tyrannus tyrannus_Eastern Kingbird",
    "Tyrannus verticalis_Western Kingbird",
    "Uraeginthus angolensis_Southern Cordonbleu",
    "Uropsila leucogastra_White-bellied Wren",
    "Urotriorchis macrourus_Long-tailed Hawk",
    "Vanellus chilensis_Southern Lapwing",
    "Vanellus miles_Masked Lapwing",
    "Vanellus vanellus_Northern Lapwing",
    "Vermivora cyanoptera_Blue-winged Warbler",
    "Vidua macroura_Pin-tailed Whydah",
    "Vireo chivi_Chivi Vireo",
    "Vireo flavifrons_Yellow-throated Vireo",
    "Vireo flavoviridis_Yellow-green Vireo",
    "Vireo gilvus_Warbling Vireo",
    "Vireo griseus_White-eyed Vireo",
    "Vireo olivaceus_Red-eyed Vireo",
    "Vireo pallens_Mangrove Vireo",
    "Vireo solitarius_Blue-headed Vireo",
    "Volatinia jacarina_Blue-black Grassquit",
    "Xanthocephalus xanthocephalus_Yellow-headed Blackbird",
    "Xenopipo atronitens_Black Manakin",
    "Xipholena punicea_Pompadour Cotinga",
    "Xiphorhynchus elegans_Elegant Woodcreeper",
    "Xiphorhynchus flavigaster_Ivory-billed Woodcreeper",
    "Xiphorhynchus guttatus_Buff-throated Woodcreeper",
    "Zapornia flavirostra_Black Crake",
    "Zenaida asiatica_White-winged Dove",
    "Zenaida auriculata_Eared Dove",
    "Zenaida macroura_Mourning Dove",
    "Zonotrichia albicollis_White-throated Sparrow",
    "Zonotrichia atricapilla_Golden-crowned Sparrow",
    "Zonotrichia leucophrys_White-crowned Sparrow",
    "Zosterops atricapilla_Black-capped White-eye",
    "Zosterops lateralis_Silvereye",
    "Zosterops simplex_Swinhoe's White-eye",
};

#endif /* APP_LABELS_H */
