/* Auto-generated by gen_app_config.py — do not edit. */
#ifndef APP_LABELS_H
#define APP_LABELS_H

#define APP_NUM_CLASSES_ACTUAL 10

static const char * const APP_LABELS[] = {
    "Common Chaffinch",
    "Common Chiffchaff",
    "Eurasian Blackbird",
    "Eurasian Blackcap",
    "Eurasian Blue Tit",
    "Great Spotted Woodpecker",
    "Great Tit",
    "Mallard",
    "Song Thrush",
    "Tawny Owl",
};

#endif /* APP_LABELS_H */
