#!/usr/bin/env python3
"""Generate app_config.h and app_labels.h from a model_config.json + labels file.

Usage:
    python gen_app_config.py MODEL_CONFIG [LABELS_FILE] [-o OUTPUT_DIR]

Reads *_model_config.json (and optionally *_labels.txt) to produce firmware
headers with the correct audio parameters, frontend mode, and class labels.

If LABELS_FILE is omitted, the script looks for a sibling *_labels.txt next
to MODEL_CONFIG (e.g. best_model_labels.txt for best_model_model_config.json).
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Optional

# Frontend string → firmware define name
_FRONTEND_MAP = {
    "hybrid": "APP_FRONTEND_HYBRID",
    "raw": "APP_FRONTEND_RAW",
    "tf": "APP_FRONTEND_RAW",
    "precomputed": "APP_FRONTEND_PRECOMPUTED",
    "librosa": "APP_FRONTEND_PRECOMPUTED",
}


def generate_app_config_h(model_cfg: dict, num_classes: int) -> str:
    """Return the full contents of ``app_config.h``."""
    sr = int(model_cfg["sample_rate"])
    chunk = model_cfg["chunk_duration"]
    fft_len = int(model_cfg["fft_length"])
    hop = int(model_cfg.get("hop_length", fft_len // 2 + 2))
    sw = int(model_cfg["spec_width"])
    num_mels = int(model_cfg.get("num_mels", 64))
    chunk_samples = int(sr * chunk)

    frontend_str = model_cfg.get("audio_frontend", "hybrid")
    frontend_define = _FRONTEND_MAP.get(frontend_str, "APP_FRONTEND_HYBRID")

    # Format chunk_duration: integer when possible, float otherwise.
    if chunk == int(chunk):
        chunk_literal = str(int(chunk))
    else:
        chunk_literal = str(chunk)

    return f"""\
/* Auto-generated by gen_app_config.py — do not edit.
 *
 * Source: model_config.json
 * Target: STM32N6570-DK  (Cortex-M55 + NPU)
 */

#ifndef APP_CONFIG_H
#define APP_CONFIG_H

/* --- NPU_Validation board support defines --------------------------------- */
/* These are required by misc_toolbox.c / system_clock_config.c from the       */
/* NPU_Validation project when building inside that tree.                      */
#ifndef NUCLEO_N6_CONFIG
#define NUCLEO_N6_CONFIG                0
#endif
#ifndef USE_MCU_DCACHE
#define USE_MCU_DCACHE                  1
#endif
#ifndef USE_MCU_ICACHE
#define USE_MCU_ICACHE                  1
#endif
#ifndef USE_EXTERNAL_MEMORY_DEVICES
#define USE_EXTERNAL_MEMORY_DEVICES     1
#endif
#ifndef USE_UART_BAUDRATE
#define USE_UART_BAUDRATE               921600
#endif
#ifndef USE_USB_PACKET_SIZE
#define USE_USB_PACKET_SIZE             512
#endif
#ifndef USE_OVERDRIVE
#define USE_OVERDRIVE                   0
#endif
/* NO_OVD_CLK400: when no overdrive, use clocks all @ 400 MHz */
/* #define NO_OVD_CLK400 */

/* --- Audio parameters (from model_config.json) ---------------------------- */
#define APP_SAMPLE_RATE       {sr}
#define APP_CHUNK_DURATION    {chunk_literal}
#define APP_CHUNK_SAMPLES     {chunk_samples}
#define APP_FFT_LENGTH        {fft_len}
#define APP_FFT_BINS          (APP_FFT_LENGTH / 2 + 1)
#define APP_HOP_LENGTH        {hop}
#define APP_SPEC_WIDTH        {sw}
#define APP_NUM_MELS          {num_mels}
#define APP_NUM_CLASSES       {num_classes}

/* --- Audio frontend mode -------------------------------------------------- */
/* 0 = hybrid:      STFT on M55 → feed [fft_bins, spec_width] to NPU         */
/* 1 = raw:         feed raw waveform [chunk_samples, 1] to NPU (no STFT)    */
/* 2 = precomputed: STFT + mel filterbank on M55 → feed [num_mels, spec_width] */
#define APP_FRONTEND_HYBRID       0
#define APP_FRONTEND_RAW          1
#define APP_FRONTEND_PRECOMPUTED  2
#define APP_AUDIO_FRONTEND        {frontend_define}

/* --- SD card paths -------------------------------------------------------- */
#define APP_AUDIO_DIR         "audio"
#define APP_RESULTS_FILE      "results.txt"

/* --- Inference ------------------------------------------------------------- */
#define APP_TOP_K             5
#define APP_SCORE_THRESHOLD   0.01f

#endif /* APP_CONFIG_H */
"""


def generate_app_labels_h(labels: list[str]) -> str:
    """Return the full contents of ``app_labels.h``."""
    n = len(labels)
    lines = [
        "/* Auto-generated by gen_app_config.py — do not edit. */",
        "#ifndef APP_LABELS_H",
        "#define APP_LABELS_H",
        "",
        f"#define APP_NUM_CLASSES_ACTUAL {n}",
        "",
        "static const char * const APP_LABELS[] = {",
    ]
    for label in labels:
        escaped = label.replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'    "{escaped}",')
    lines += [
        "};",
        "",
        "#endif /* APP_LABELS_H */",
        "",
    ]
    return "\n".join(lines)


def _guess_labels_path(config_path: Path) -> Optional[Path]:
    """Guess the labels file path from the model config path.

    best_model_model_config.json → best_model_labels.txt
    """
    name = config_path.name
    stem = name.replace("_model_config.json", "")
    candidate = config_path.parent / f"{stem}_labels.txt"
    return candidate if candidate.is_file() else None


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("model_config", type=Path, help="Path to *_model_config.json")
    parser.add_argument("labels_file", type=Path, nargs="?", default=None,
                        help="Path to *_labels.txt (auto-detected if omitted)")
    parser.add_argument("-o", "--output-dir", type=Path, default=None,
                        help="Output directory for headers (default: Inc/)")
    args = parser.parse_args()

    # Load model config
    with open(args.model_config) as f:
        model_cfg = json.load(f)

    # Resolve labels file
    labels_path = args.labels_file or _guess_labels_path(args.model_config)
    if labels_path and labels_path.is_file():
        labels = [line.strip() for line in labels_path.read_text().splitlines() if line.strip()]
    else:
        labels = model_cfg.get("class_names", [])
        if not labels:
            print(f"[WARN] No labels file found and no class_names in config; "
                  f"using generic labels", file=sys.stderr)
            n = model_cfg.get("num_classes", 10)
            labels = [f"class_{i}" for i in range(n)]

    num_classes = len(labels)

    # Output directory
    script_dir = Path(__file__).resolve().parent
    out_dir = args.output_dir or script_dir / "Inc"
    out_dir.mkdir(parents=True, exist_ok=True)

    # Write app_config.h
    config_h = out_dir / "app_config.h"
    config_h.write_text(generate_app_config_h(model_cfg, num_classes))
    print(f"[OK] {config_h}  (sr={model_cfg['sample_rate']}, "
          f"chunk={model_cfg['chunk_duration']}s, "
          f"samples={int(model_cfg['sample_rate'] * model_cfg['chunk_duration'])}, "
          f"frontend={model_cfg.get('audio_frontend', 'hybrid')}, "
          f"classes={num_classes})")

    # Write app_labels.h
    labels_h = out_dir / "app_labels.h"
    labels_h.write_text(generate_app_labels_h(labels))
    print(f"[OK] {labels_h}  ({num_classes} labels)")


if __name__ == "__main__":
    main()
